refactor(gateway): switch to 74 byte UDP packet format for IP discovery
nextcord/nextcord pull request #1005
Opened 2023-03-08 23:08 UTC by anoadragon453

## Summary

This PR updates Nextcord to use the new UDP packet format for [discovering your external IP address and port](https://discord.com/developers/docs/topics/voice-connections#ip-discovery) against Discord's VoIP servers.

Discord announced in their guild that on **March 15th, 2023**, all VoIP servers would be updated to **only** accept the 74-byte packet length, and would no longer accept the 70-byte packet length format which nextcord currently uses.

![image](https://user-images.githubusercontent.com/1342360/223873328-eb56a489-de62-4a1a-a6e6-4cca050e2273.png)

disnake made [a similar change](https://github.com/DisnakeDev/disnake/pull/967) to their library in their most recent release.

## Checklist

- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [?] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-03-08 23:49 UTC, Skelmis approved these changes

2023-03-09 00:02 UTC, teaishealthy requested changes

2023-03-09 00:02 UTC, teaishealthy commented on nextcord/gateway.py
> +        # https://discord.com/developers/docs/topics/voice-connections#ip-discovery
```suggestion
        # https://discord.dev/topics/voice-connections#ip-discovery
```

2023-03-11 20:18 UTC, teaishealthy approved these changes

2023-03-11 20:18 UTC, ooliver1 approved these changes

2023-03-11 20:19 UTC, merged