fix(colour): use new dark theme colour
nextcord/nextcord pull request #1006
Opened 2023-03-09 12:13 UTC by toolifelesstocode

## Summary

The dark theme colour on the UI recently changed and so therefore this has changed `nextcord.Colour.dark_theme()` to use the new colour.

## Checklist

- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-03-11 20:16 UTC, ooliver1 requested changes

2023-03-11 20:16 UTC, ooliver1 commented on nextcord/colour.py
>          .. versionadded:: 1.5
Maybe this could benefit with a `.. versionchanged::`

2023-03-11 23:56 UTC, teaishealthy approved these changes
Just ooliver's comment, other than that lgtm :+1:

2023-03-12 08:35 UTC, ooliver1 commented
What benefit do you get from the old dark theme? You cannot access it anymore

2023-03-20 07:46 UTC, toolifelesstocode commented
Not sure if I was suppose to use 'color' or 'colour' but I figured it doesn't matter much.

2023-03-20 14:59 UTC, ooliver1 approved these changes

2023-03-20 14:59 UTC, merged