Add invitable argument in TextChannel.create_thread method
nextcord/nextcord pull request #1007
Opened 2023-03-09 19:22 UTC by Kevin-OVI

## Summary

The `invitable` argument was not present in the `TextChannel.create_thread` method for some reason even if the underlying state supported it, so I added it.

## Checklist

- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-03-11 20:17 UTC, teaishealthy commented on nextcord/channel.py
> +            Only available for private threads and without message.
>  and without message.

Could you elaborate on what this means?

2023-03-11 20:25 UTC, ooliver1 requested changes

2023-03-11 20:25 UTC, ooliver1 commented on nextcord/channel.py
> +            Only available for private threads and without message.
```suggestion
            Only available for private threads and created without ``message``.
```
It isn't too clear as to what "and without message" means (as seen above).

2023-03-11 23:52 UTC, teaishealthy requested changes

2023-03-11 23:52 UTC, teaishealthy commented on nextcord/channel.py
> +            Only available for private threads and created without ``message``.
```suggestion
            Only available for private threads and threads created without a ``message``.
```

2023-03-12 17:35 UTC, ooliver1 commented on nextcord/channel.py
> +        invitable: bool = True,
Ideally this should default to `None`, which means "default to Discord's default" (by not adding unnecessary fields to the payload)

2023-03-12 17:36 UTC, ooliver1 approved these changes

2023-03-12 18:50 UTC, teaishealthy approved these changes

2023-03-20 14:57 UTC, merged