fix: incomplete payloads leading to tracebacks within autocomplete
nextcord/nextcord pull request #1008
Opened 2023-03-11 03:30 UTC by Skelmis

## Summary

When using either a `nextcord.User` or `nextcord.Member` item within autocomplete there is a chance that the required data is missing due to discord not sending the data. This PR fixes the raw tracebacks and instead takes a best effort approach to attempting to get a valid object from cache before returning atleast a `nextcord.Object` object.

#### Reproduction code

```py

@client.slash_command()
async def test(
    interaction: nextcord.Interaction,
    member: nextcord.Member = nextcord.SlashOption(
        name="member", description="Select member", required=True
    ),
    warn: int = nextcord.SlashOption(name="warn", description="Warn", required=True),
):
    print(type(member))

@test.on_autocomplete("warn")
async def warn_autocomplete(interaction: nextcord.Interaction, warn: int, member: nextcord.Member):
    print(type(member))

    return await interaction.response.send_autocomplete([str(i) for i in range(10)])
```

## Checklist

- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-03-11 20:04 UTC, teaishealthy requested changes

2023-03-11 20:04 UTC, teaishealthy commented on nextcord/application_command.py
> +                data = cast(ApplicationCommandInteractionData, data)
```suggestion
                data = cast(ApplicationCommandInteractionData, interaction.data)
```

2023-03-11 20:04 UTC, teaishealthy commented on nextcord/application_command.py
> +                        value = guild.get_member(user_id)
```suggestion
                if guild_id := data.get("guild_id"):
                    if guild := state._guilds.get(int(guild_id)):
                        value = guild.get_member(user_id)
```

2023-03-11 20:04 UTC, teaishealthy commented on nextcord/application_command.py
> +            :py:class:`nextcord.Object` depending on the data discord sends.
```suggestion
            :py:class:`nextcord.Object` depending on the data Discord sends.
```

2023-03-11 20:04 UTC, teaishealthy commented on nextcord/application_command.py
> +            If you are using :py:class:`nextcord.Member` or :py:class:`nextcord.user` typehints in
```suggestion
            If you are using :py:class:`nextcord.Member` or :py:class:`nextcord.User` typehints in
```

2023-03-11 20:05 UTC, ooliver1 requested changes

2023-03-11 20:05 UTC, ooliver1 commented on nextcord/application_command.py
> +            If you are using :py:class:`nextcord.Member` or :py:class:`nextcord.user` typehints in
```suggestion
            If you are using :class:`nextcord.Member` or :class:`nextcord.user` typehints in
```
Sphinx knows it is Python

2023-03-11 20:05 UTC, ooliver1 commented on nextcord/application_command.py
> +            :py:class:`nextcord.Object` depending on the data discord sends.
```suggestion
            :class:`nextcord.Object` depending on the data discord sends.
```

2023-03-12 17:55 UTC, alentoghostflame approved these changes
I haven't tested it myself, but I assume normal command usage and not JUST autocomplete has been tested already.
LGTM.

2023-03-12 18:49 UTC, teaishealthy requested changes

2023-03-12 18:49 UTC, teaishealthy commented on nextcord/application_command.py
> +                    value = Object(id=user_id)
```suggestion
                    value = state._users.get(user_id)

                    if value is None:
                        # Fall back to a Object at-least
                        value = Object(id=user_id)
```

Check unnecessary if first if was False

2023-03-12 22:17 UTC, teaishealthy approved these changes

2023-04-09 12:45 UTC, Skelmis commented
Ah well, I can't figure out how to dismiss reviews

2023-07-12 18:08 UTC, ooliver1 approved these changes

2023-07-12 18:08 UTC, merged