feat(flags): add auto moderation
nextcord/nextcord pull request #1026
Opened 2023-03-31 08:28 UTC by toolifelesstocode

## Summary

Implements discord/discord-api-docs#6021

Note that I am unsure if the name of the flag is okay, I've just used what it was called in the documentation.

## Checklist

- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-04-07 14:23 UTC, toolifelesstocode commented
The client does say that, however, remember that some names on the client are different on the API. Such as how there is 'guild' and 'server'

2023-04-09 12:20 UTC, Skelmis approved these changes
Looks good to me, i also agree with the naming as it keeps it consistent. All other values in the class mirror the documentation 1-1 so while this can be considered long it would also be consistent with both the class and discord docs

2023-04-12 19:59 UTC, ooliver1 requested changes

2023-04-12 19:59 UTC, ooliver1 commented on nextcord/flags.py
> +        """:class:`bool`: Returns ``True`` if the application uses the Auto Moderation API."""
```suggestion
        """:class:`bool`: Returns ``True`` if the application uses the Auto Moderation API.

        .. versionadded:: 2.5
        """
```

2023-06-15 01:16 UTC, EmreTech approved these changes

2023-06-15 01:16 UTC, EmreTech commented on nextcord/flags.py
> +        .. versionadded:: 2.5
```suggestion
        .. versionadded:: 2.6
```

2023-06-15 01:19 UTC, merged