feat: see all permissions required to run a command
nextcord/nextcord pull request #1065
Opened 2023-06-14 22:46 UTC by EmreTech

## Summary

This PR reopens PR #618, which implemented a new way to see the permissions required to run a command. Closes #511.

## Checklist

- [ ] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-06-14 22:51 UTC, Skelmis requested changes
There is a better way to do this which is to only set the attribute on initial call and not every time the command is invoked which was why this PR was originally closed due to the work required to accomplish it.

This rework requires changing the decors to have more nesting to allow for setting on the initial invoke as well as still supporting the checks themselves

2023-06-14 23:08 UTC, EmreTech commented
> There is a better way to do this which is to only set the attribute on initial call and not every time the command is invoked which was why this PR was originally closed due to the work required to accomplish it.
> 
> This rework requires changing the decors to have more nesting to allow for setting on the initial invoke as well as still supporting the checks themselves.
> 
> This was discussed between myself and arl somewhere, hence why the last PR got closed. Didn't realize it wasn't documented.
> 
> If enough people are happy with the current approach however I will change this review to approval

I think setting the attribute on the initial call would be a much better approach. I'll try to rewrite the PR to accomplish that.

2023-06-25 10:30 UTC, Skelmis requested changes
Might as well add this to `ext.application_checks` as well in this PR

2023-07-13 09:47 UTC, Skelmis requested changes
Overall I approve, however the callback setters overlap such that this code says the test slash command requires manage guild perms when it does not.

```py
import asyncio
import os

from nextcord.ext import commands

bot = commands.Bot()


@bot.event
async def on_ready():
    await asyncio.sleep(5)
    cmd = bot.get_application_commands()[0]
    print(cmd.required_permissions)


@bot.slash_command()
@commands.has_permissions(manage_guild=True)
async def test(ctx):
    await ctx.send("Test")

bot.run(os.environ["TOKEN"])
```

2023-07-14 02:57 UTC, Skelmis commented
> > Overall I approve, however the callback setters overlap such that this code says the test slash command requires manage guild perms when it does not.
> > ```python
> > import asyncio
> > import os
> > 
> > from nextcord.ext import commands
> > 
> > bot = commands.Bot()
> > 
> > 
> > @bot.event
> > async def on_ready():
> >     await asyncio.sleep(5)
> >     cmd = bot.get_application_commands()[0]
> >     print(cmd.required_permissions)
> > 
> > 
> > @bot.slash_command()
> > @commands.has_permissions(manage_guild=True)
> > async def test(ctx):
> >     await ctx.send("Test")
> > 
> > bot.run(os.environ["TOKEN"])
> > ```
> 
> Can you elaborate? I don't understand what you mean by "requires manage guild perms when it does not" in this example.

Well the way to set perms for slash commands in nextcord is via `ext.application_checks`

2023-07-14 05:18 UTC, EmreTech commented
> > > Overall I approve, however the callback setters overlap such that this code says the test slash command requires manage guild perms when it does not.
> > > ```python
> > > import asyncio
> > > import os
> > > 
> > > from nextcord.ext import commands
> > > 
> > > bot = commands.Bot()
> > > 
> > > 
> > > @bot.event
> > > async def on_ready():
> > >     await asyncio.sleep(5)
> > >     cmd = bot.get_application_commands()[0]
> > >     print(cmd.required_permissions)
> > > 
> > > 
> > > @bot.slash_command()
> > > @commands.has_permissions(manage_guild=True)
> > > async def test(ctx):
> > >     await ctx.send("Test")
> > > 
> > > bot.run(os.environ["TOKEN"])
> > > ```
> > 
> > 
> > Can you elaborate? I don't understand what you mean by "requires manage guild perms when it does not" in this example.
> 
> Well the way to set perms for slash commands in nextcord is via `ext.application_checks`

I tested your example code, and the checks from `ext.commands` do work on application commands, but not the other way around. Are you asking me to check the type of the command passed into the decorators?

2023-07-17 06:04 UTC, Skelmis approved these changes

2023-07-31 13:55 UTC, teaishealthy requested changes

2023-07-31 13:55 UTC, teaishealthy commented on nextcord/ext/application_checks/core.py
> +    predicate: "ApplicationCheck", name: str, perms: Dict[str, bool]
```suggestion
    predicate: ApplicationCheck, name: str, perms: Dict[str, bool]
```

2023-08-02 20:34 UTC, teaishealthy approved these changes

2023-08-02 22:49 UTC, merged