feat(guild): add premium_progress_bar_enabled
nextcord/nextcord pull request #1067
Opened 2023-06-16 12:28 UTC by ooliver1

## Summary

discord/discord-api-docs#4001

## Checklist

- [x] I have tested my changes.
- [x] I have updated the documentation to reflect the changes.
- [x] I have run `task pyright` and fixed the relevant issues.

2023-06-16 12:34 UTC, spifory requested changes

2023-06-16 12:34 UTC, spifory commented on nextcord/guild.py
> -            .. versionadded:: 2.4
Does this have to be removed?

2023-06-16 12:34 UTC, spifory commented on nextcord/guild.py
> +        self._premium_progress_bar_enabled: bool = guild.get("premium_progress_bar_enabled", False)
```suggestion
        self._premium_progress_bar_enabled: bool = guild["premium_progress_bar_enabled"]
```
Seeing as this return `true` or `false` and not `null`, the `.get` isn't really needed

2023-06-16 12:34 UTC, spifory commented on nextcord/guild.py
> +            Whether the premium guild boost progress bar is enabled in this guild.
```suggestion
            Whether the premium guild boost progress bar is enabled.
```

2023-06-16 12:35 UTC, spifory commented on nextcord/guild.py
> +            Whether the premium guild boost progress bar is enabled in this guild.
Alternatively, ```suggestion
Whether the boost progress bar is enabled in this guild.
```

2023-06-16 12:48 UTC, spifory approved these changes

2023-06-16 15:41 UTC, EmreTech approved these changes

2023-06-24 06:25 UTC, Skelmis approved these changes

2023-06-24 06:25 UTC, merged