feat: add member profile automod fields
nextcord/nextcord pull request #1087
Opened 2023-07-10 21:43 UTC by spifory

## Summary

- Implements discord/discord-api-docs#6040

Although, this has not been released, as far as I am aware.

## This is a **Code Change**

- [ ] I have tested my changes.
- [x] I have updated the documentation to reflect the changes.
- [x] I have run `task pyright` and fixed the relevant issues.

2023-07-11 08:05 UTC, ooliver1 commented
Draft as this is waiting on a docs PR.

2024-06-24 13:26 UTC, ooliver1 requested changes

2024-06-24 13:26 UTC, ooliver1 commented on nextcord/auto_moderation.py
> +            :attr:`AutoModerationTriggerType.keyword_preset` or :attr:`AutoModerationTriggerType.member_profile`.
This is not true for presets.

2024-07-18 12:18 UTC, ooliver1 commented on nextcord/auto_moderation.py
> +            :attr:`AutoModerationTriggerType.keyword_preset`
```suggestion
            :attr:`AutoModerationTriggerType.keyword_preset`.
```

2024-07-18 12:19 UTC, ooliver1 requested changes

2024-07-18 12:19 UTC, ooliver1 commented on nextcord/enums.py
> +    member_update = 2
This is not a trigger type. Member profiles is covered in type `6`.
![image](https://github.com/user-attachments/assets/421e0404-3899-424b-8640-d0ba8039488f)

2024-09-09 12:39 UTC, spifory commented
Tested with 
```py
from typing import Optional

from nextcord import Intents, Interaction, Member, Permissions
from nextcord.ext.commands import Bot

bot = Bot(
    intents=Intents(guilds=True, message_content=True, messages=True),
    default_guild_ids=[...],
)

@bot.slash_command(default_member_permissions=Permissions(manage_events=True))
async def perms(inter: Interaction, user: Optional[Member]):
    assert inter.user is not None
    assert isinstance(inter.user, Member)
    perms = inter.channel.permissions_for(user or inter.user)
    return await inter.send(f"ev: {perms.create_events}\nexp: {perms.create_expressions}")

bot.run(...)
```
![image](https://github.com/user-attachments/assets/c3d89430-6ff9-4ddc-8f19-c91a20f05c96)
![image](https://github.com/user-attachments/assets/5e57d811-0545-4697-9c8c-1a3d61348b54)
(tested two different people)

2025-04-28 18:01 UTC, ooliver1 approved these changes

2026-05-19 16:37 UTC, merged