feat(iterators): add `GuildIterator.with_counts`
nextcord/nextcord pull request #1093
Opened 2023-07-18 07:31 UTC by spifory

## Summary

Implements discord/discord-api-docs#5628

In case you're wondering, "why is the default for `with_counts` `False`?"
Well that is because the default on the documentation `false`, so just for the sake of consistency, that is why the default is `False`.

## This is a **Code Change**

- [ ] I have tested my changes.
- [x] I have updated the documentation to reflect the changes.
- [x] I have run `task pyright` and fixed the relevant issues.

2023-07-18 07:38 UTC, spifory commented
I accidentally made this branch off of another branch, and not master, so that is the reason for the force-pushes

2023-07-26 10:24 UTC, teaishealthy requested changes

2023-07-26 10:24 UTC, teaishealthy commented on nextcord/iterators.py
> +        Defaults to ``True``.
I don't think so
```suggestion
        Defaults to ``False``.
```

2023-07-26 10:42 UTC, teaishealthy approved these changes
is probably ok :rocket:

2023-08-12 01:01 UTC, EmreTech requested changes

2023-08-13 09:03 UTC, spifory commented on nextcord/iterators.py
> +        self, retrieve: int, with_counts: bool = False
I wasn't thinking that it couldn't be used in both, I just figured I might have to add the parameter to that function as well.

2023-08-13 15:00 UTC, EmreTech requested changes
This PR fails testing. I got an [exception](https://workbin.dev/?id=1691938674796779) that yarl (which aiohttp uses for query parameters) doesn't support booleans.

You have to do something like `HTTPClient.get_guild`:
https://github.com/nextcord/nextcord/blob/a4bd5d2482614e8098c180c0e69100a0e5317b4d/nextcord/http.py#L1360

2023-08-15 12:50 UTC, spifory commented
@EmreTech https://github.com/nextcord/nextcord/pull/1093/commits/244899b6ccd99e2556564a871648a95f53ab9014

2023-08-15 17:29 UTC, EmreTech approved these changes
Tested.

2023-08-25 23:58 UTC, ooliver1 approved these changes

2023-08-25 23:58 UTC, merged