feat(utils): add format_ts
nextcord/nextcord pull request #1099
Opened 2023-07-26 10:14 UTC by teaishealthy

## Summary

Create a new function `format_ts` that can format a unix timestamp, format_dt can use this function too to reduce code duplication.

Closes #1085 

## This is a **Code Change**

- [x] I have tested my changes.
- [x] I have updated the documentation to reflect the changes.
- [x] I have run `task pyright` and fixed the relevant issues.

2023-07-26 18:59 UTC, spifory requested changes
And also it's not too important but you may want to add a `versionchanged` to `format_dt`.

2023-07-26 18:59 UTC, spifory commented on nextcord/utils.py
> +    return format_ts(int(dt.timestamp()), style=style)
No need to re-int an integer
```suggestion
    return format_ts(dt.timestamp(), style=style)
```

2023-07-26 18:59 UTC, spifory commented on nextcord/utils.py
> +    """A helper function to format an :class:`int` unix timestamp for presentation within Discord.
```suggestion
    """A helper function to format a Unix timestamp as an :class:`int` for presentation within Discord.
```

2023-07-26 18:59 UTC, spifory commented on nextcord/utils.py
> +        The unix timestamp to format.
```suggestion
        The Unix timestamp to format.
```

2023-07-26 18:59 UTC, spifory commented on nextcord/utils.py
> +        The style to format the datetime with.
```suggestion
        The style to format the timestamp with.
```

2023-07-26 18:59 UTC, spifory commented on nextcord/utils.py
> +    if not isinstance(ts, int):  # pyright: ignore[reportUnnecessaryIsInstance]
While I do understand that `format_dt` initially did this, _is_ this actually needed? `ts` is already typed as an integer so is there really a need to check if it's an integer a second time?

2023-07-26 18:59 UTC, spifory commented on nextcord/utils.py
>      if not isinstance(dt, datetime.datetime):  # pyright: ignore[reportUnnecessaryIsInstance]
Same question about checking the type again

2023-07-26 19:37 UTC, teaishealthy commented on nextcord/utils.py
> +    return format_ts(int(dt.timestamp()), style=style)
Its a float

2023-07-26 22:28 UTC, teaishealthy commented
> And also it's not too important but you may want to add a `versionchanged` to `format_dt`.
@spifory 
The external api for format_dt did not change, no reason to.

2023-08-03 05:45 UTC, EmreTech approved these changes

2023-08-07 07:37 UTC, spifory approved these changes

2023-09-19 22:48 UTC, ooliver1 approved these changes

2023-09-19 22:48 UTC, merged