fix: make ``state`` fallback to ``name` ` for CustomActivity
nextcord/nextcord pull request #1109
Opened 2023-08-13 14:11 UTC by Soheab

## Summary

This PR documents the `state` attribute on `CustomActivity` and makes it fallbacks to `name` instead of `None` if not provided.

This allows users to do the following:
```py
nextcord.CustomActivity(
  name = "Nextcord is the best!"
)  
```
Instead of:
```py
nextcord.CustomActivity(
  name = "Custom Status",
  state = "Nextcord is the best!"
)
# this still works tho.
```

## This is a **Code Change**

- [x] I have tested my changes.
- [x] I have updated the documentation to reflect the changes.
- [x] I have run `task pyright` and fixed the relevant issues.

2023-08-13 14:16 UTC, ooliver1 requested changes

2023-08-13 14:16 UTC, ooliver1 commented on nextcord/activity.py
> +        The custom status text. :attr:`~.CustomActivity.name` must equal to "Custom Status" for this to work.
```suggestion
        The custom status text. :attr:`~.CustomActivity.name` must equal "Custom Status" for this to work.
```

2023-08-26 00:16 UTC, ooliver1 commented on nextcord/activity.py
> +            Fallsback to :attr:`~.CustomActivity.name` if not provided.
```suggestion
            This falls back to :attr:`~.CustomActivity.name` if not provided.
```

2023-09-17 04:07 UTC, EmreTech approved these changes
Tested.

2023-09-19 22:49 UTC, ooliver1 approved these changes

2023-09-19 22:49 UTC, merged