feat: add voice messages
nextcord/nextcord pull request #1111
Opened 2023-08-15 14:05 UTC by spifory

## Summary

Implements discord/discord-api-docs#6082

## This is a **Code Change**

- [ ] I have tested my changes.
- [x] I have updated the documentation to reflect the changes.
- [x] I have run `task pyright` and fixed the relevant issues.

2023-08-16 23:04 UTC, EmreTech requested changes

2023-08-16 23:04 UTC, EmreTech commented on nextcord/types/message.py
> +    waveform: Optional[str]
```suggestion
    duration_secs: NotRequired[float]
    waveform: NotRequired[str]
```

2023-08-16 23:04 UTC, EmreTech commented on nextcord/message.py
> +            return bytearray(self.waveform)
```suggestion
            return bytearray(self._waveform)
```

2023-08-17 08:18 UTC, EmreTech approved these changes
Untested.

2023-10-01 07:08 UTC, teaishealthy commented
Update versionadded

2023-10-01 09:14 UTC, teaishealthy requested changes

2023-10-01 09:14 UTC, teaishealthy commented on nextcord/message.py
> +        """Optional[array[:class:`int`]]: The base64 decoded representing a sampled waveform
```suggestion
        """Optional[array[:class:`int`]]: The base64 decoded data representing a sampled waveform
```

2023-10-09 10:44 UTC, teaishealthy requested changes

2023-10-09 10:44 UTC, teaishealthy commented on nextcord/message.py
> +            return array("B", [int(b) for b in base64.b64decode(self._waveform)])
This is not a cheap conversion, especially with more data. Make this an `utils.cached_property`

2023-10-09 10:46 UTC, teaishealthy commented
Fix the Ruff issues and update your fork

2024-01-15 10:29 UTC, Skelmis commented
Any update on this PR?

2024-01-16 06:44 UTC, spifory commented
> Any update on this PR?

I forgot about this sorry

2024-05-20 10:22 UTC, teaishealthy requested changes

2024-05-20 10:22 UTC, teaishealthy commented on nextcord/message.py
> +            return array("B", [int(b) for b in base64.b64decode(self._waveform)])
```suggestion
            return array("B", base64.b64decode(self._waveform))
```

`base64.b64decode` returns `bytes` which when iterated return `int`

2024-09-07 12:47 UTC, Skelmis approved these changes
Untested, lines up with expectations

2024-09-07 12:48 UTC, Skelmis commented
@teaishealthy care to re-review this?

2024-12-22 11:28 UTC, vcokltfre approved these changes
Tested working. Code looks good.

2024-12-22 11:29 UTC, merged