chore: add missing fields for stage instance
nextcord/nextcord pull request #1132
Opened 2023-10-01 18:32 UTC by Soheab

## Summary

Fixes: #934 

This PR adds some missing fields to stage instance.

Adds the following to `StageChannel.create_instance`:
- `send_start_notification`
- `scheduled_event`

And to `StageInstance`:
- `scheduled_event_id`
- `scheduled_event`

Relevant API Docs:
https://discord.com/developers/docs/resources/stage-instance#create-stage-instance
`guild_scheduled_event_id` was added recently: https://github.com/discord/discord-api-docs/commit/67ce08b1e300c63e5a1e362838e21fb3fc7b1fcc

<!--
## This is a **Code Change**

- [ ] I have tested my changes.
- [ ] I have updated the documentation to reflect the changes.
- [ ] I have run `task pyright` and fixed the relevant issues.

2023-11-03 22:45 UTC, Skelmis approved these changes

2024-07-20 05:25 UTC, xXenvy reviewed
Also versionadded needs an update

2024-07-20 05:25 UTC, xXenvy commented on nextcord/stage_instance.py
> +        return self._state.get_scheduled_event(self.scheduled_event_id)
```suggestion
        if self.scheduled_event_id is not None:
            return self._state.get_scheduled_event(self.scheduled_event_id)
```

2024-07-25 19:58 UTC, teaishealthy commented on nextcord/stage_instance.py
> +        return self._state.get_scheduled_event(self.scheduled_event_id)
I **think** a Ruff rule requires an explicit `return None`

2024-08-10 20:42 UTC, EmmmaTech requested changes
Looks good, just update all the `versionadded`s to `3.0`.

2024-09-07 12:45 UTC, Skelmis commented
@EmmmaTech care to approve now the versionadded's are resolved?

2024-09-07 13:57 UTC, EmmmaTech approved these changes
looks good :3

2024-09-08 05:38 UTC, merged