[WIP] chore: move enum docs to
nextcord/nextcord pull request #1136
Opened 2023-10-09 14:34 UTC by Soheab

## Summary

For 3.0

2023-10-10 11:48 UTC, teaishealthy commented
Looks good so far, really like the values shown in the docs now. Just don't forget to add the version directives back

2023-11-03 22:50 UTC, Skelmis requested changes

2023-11-03 22:50 UTC, Skelmis commented on nextcord/enums.py
> +    """The user is am Early Verified Bot Developer."""
```suggestion
    """The user is an Early Verified Bot Developer."""
```

2023-11-03 22:51 UTC, Skelmis approved these changes

2023-12-09 16:17 UTC, ooliver1 approved these changes
Much appreciated

2023-12-09 16:17 UTC, merged