feat: add list of webhooks to forum, stage, and voice channels
nextcord/nextcord pull request #1177
Opened 2024-04-02 22:59 UTC by acco4321

## Summary
Adds .webhooks to ForumChannels, StageChannels, and VoiceChannels.

Resolves #1176 

## This is a **Code Change**

- [x] I have tested my changes.
- [x] I have updated the documentation to reflect the changes.
- [x] I have run `task pyright` and fixed the relevant issues.

2024-05-18 01:19 UTC, EmreTech requested changes
Looks good otherwise!

2024-05-18 01:19 UTC, EmreTech commented on nextcord/channel.py
> +        .. versionadded:: 2.6
```suggestion
        .. versionadded:: 3.0
```

2024-05-18 01:19 UTC, EmreTech commented on nextcord/channel.py
> +        .. versionadded:: 2.6
```suggestion
        .. versionadded:: 3.0
```

2024-05-18 01:19 UTC, EmreTech commented on nextcord/channel.py
> +        .. versionadded:: 2.6
```suggestion
        .. versionadded:: 3.0
```

2024-06-05 14:18 UTC, EmreTech approved these changes

2024-06-14 07:32 UTC, Skelmis approved these changes

2024-06-14 07:35 UTC, merged