add nextcord.Spotify.elapsed
nextcord/nextcord pull request #188
Opened 2021-09-29 20:41 UTC by ooliver1

## Summary

closes #117
uses tz aware time to calculate the elapsed time since a current spotify activity song started

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

++I cant tell if theres any autoformatting here, it doesnt show in editor but shows sometimes on github

2021-09-30 11:15 UTC, TAG-Epic requested changes

2021-09-30 11:15 UTC, TAG-Epic commented on nextcord/activity.py
> +        self.application_id: Optional[int] = _get_as_snowflake(
Autoformatting was turned on, please revert your autoformatter's changes

2021-09-30 11:31 UTC, veni-vidi-code requested changes

2021-09-30 11:31 UTC, veni-vidi-code commented on nextcord/activity.py
> +        return datetime.datetime.now(datetime.timezone.utc) - self.start
https://nextcord.readthedocs.io/en/latest/api.html#nextcord.utils.utcnow should be prefered

2021-09-30 14:53 UTC, ooliver1 commented on nextcord/activity.py
> +        self.application_id: Optional[int] = _get_as_snowflake(
Ah fuck

2021-09-30 14:58 UTC, veni-vidi-code approved these changes

2021-09-30 15:20 UTC, ooliver1 commented
@TAG-Epic

2021-09-30 15:54 UTC, veni-vidi-code commented
LGTM

2021-10-03 12:07 UTC, TAG-Epic requested changes
Maybe add elapsed to repr?

2021-11-30 16:02 UTC, ooliver1 commented
This is quite stale and it's honestly useless, only made it to attempt the issue

2021-11-30 16:03 UTC, closed without merging