Addition of role icons
nextcord/nextcord pull request #195
Opened 2021-10-04 15:41 UTC by veni-vidi-code

## Summary

Adds new role icons to the libary

## Checklist

- [ ] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

Please note: Since i have no server to hand which already uses role icons or where i would be allowed to test them (i am still waiting for the reply of the others in charge for them) i was unable to test them so far. If you can test go ahead

2021-10-04 17:28 UTC, HexCodeFFF commented
I own a level 3 server, I'll give this a test in a bit.

2021-11-08 20:23 UTC, parker02311 approved these changes
lgtm

2021-11-25 15:53 UTC, ooliver1 requested changes

2021-11-25 15:53 UTC, ooliver1 commented on nextcord/guild.py
> +
hm whats this for

2021-11-25 15:53 UTC, ooliver1 commented on nextcord/guild.py
> +        icon: Optional[Union[:class:`str`, :class:`bytes`]
forgot to close the ``Optional[]``

2021-12-12 09:52 UTC, Skelmis commented
@veni-vidi-code any updates on this?

2021-12-15 15:17 UTC, veni-vidi-code commented on nextcord/guild.py
> +        icon: Optional[Union[:class:`str`, :class:`bytes`]
```suggestion
        icon: Optional[Union[:class:`str`, :class:`bytes`]]
```

2021-12-15 15:18 UTC, veni-vidi-code commented on nextcord/guild.py
> +
```suggestion
```

2021-12-31 23:35 UTC, vcokltfre approved these changes

2022-01-09 13:31 UTC, merged