Add webhook example
nextcord/nextcord pull request #211
Opened 2021-10-10 02:36 UTC by Suven-p

## Summary

Fixes #176 
## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2021-11-14 20:55 UTC, TAG-Epic reviewed
Possibly add a docstring to the file to explain things like the other examples

2021-11-27 10:04 UTC, ooliver1 approved these changes
assumed its tested

2021-12-12 09:57 UTC, vcokltfre requested changes

2021-12-12 09:57 UTC, vcokltfre commented on examples/webhook.py
> +loop = asyncio.get_event_loop()
This is not the preferred way of doing this in Python anymore. Instead It's recommended you use `asyncio.run()`.

i.e.
```py
asyncio.run(send_to_webhook("url", "Hello, world!"))
```

2021-12-12 10:00 UTC, ooliver1 commented on examples/webhook.py
> +loop.run_until_complete(send_to_webhook('url', 'Hello, world!'))
```suggestion
asyncio.run(send_to_webhook("url", "Hello, world!"))
```
cleaned up to a suggestion

2021-12-12 10:08 UTC, merged