Feature/voice rec/main
nextcord/nextcord pull request #224
Opened 2021-10-22 22:22 UTC by veni-vidi-code

## Summary

Implementation of basic voice recording
Closes #54 

This is a work in progress based on https://github.com/Rapptz/discord.py/pull/6507 but also working with multiple speakers

TODO
- [x] Document this code
- [x] Rework the example
- [x] Test it with more than 2 users
- [x] Stress test it over long recordings
- [x] Find out why muting does not produce a gap
- [x] Work on filters
- [x] Document filters
- [x] Test all Encoding types

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-10-30 20:50 UTC, Sheepposu requested changes

2021-11-08 04:24 UTC, VincentRPS approved these changes
lgtm

2021-11-13 04:43 UTC, VincentRPS requested changes
just a suggestion ext.voicerecording imo is too long maybe you can name it ext.audio or ext.rec

2021-12-06 07:32 UTC, RPSMain approved these changes

2021-12-06 07:50 UTC, ooliver1 commented on nextcord/errors.py
> +    """Exception that's thrown when trying to listen while already listening"""
If you do this change, make sure it's not over 75 lines or whatever it is for docstrings

2021-12-29 14:39 UTC, TAG-Epic requested changes
Honestly I dislike the current voice receive api and we should definitely not store files to the users system without them doing it..

2022-06-19 20:45 UTC, ooliver1 commented
im gonna close this for now as its been stale for a while, feel free to reopen this once progress resumes

2022-06-19 20:45 UTC, closed without merging

2023-01-01 09:13 UTC, Mistobaan commented
What happened to this PR? @ooliver1 stale dev is the only issue?

2023-12-04 16:10 UTC, laithalshabi commented
how to use it where is the documentation <3