Create CODEOWNERS
nextcord/nextcord pull request #242
Opened 2021-11-01 20:57 UTC by veni-vidi-code

First Codeowners

## Summary

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2021-11-02 03:24 UTC, VincentRPS commented
i forgor 💀 what is codeowners for?

2021-11-02 08:16 UTC, VincentRPS approved these changes
When the imposter is a sussy baka

2021-11-02 13:08 UTC, Questia reviewed
by the way i just changed my github name and basically everyother name so you might wanna change that

2021-11-07 00:52 UTC, VincentRPS reviewed
why this hasn't been merged yet?

2021-11-07 22:09 UTC, TAG-Epic requested changes

2021-11-07 22:09 UTC, TAG-Epic commented on .github/CODEOWNERS
> +# You can apply for codeownership on our discord server
Not spesific enough, should specify how and where.

2021-11-07 22:09 UTC, TAG-Epic commented on .github/CODEOWNERS
> +# Voice Rec
```suggestion
# Voice Recording
```

Unmerged, should not be added yet.

2021-11-08 04:18 UTC, VincentRPS commented on .github/CODEOWNERS
> +# Slash Commands
same with what epic said this shouldn't be added(or at least commented) until it is merged

2021-11-08 04:20 UTC, VincentRPS commented on .github/CODEOWNERS
> +# Slash Commands
Specify Better
```suggestion
# Application And Interaction Commands
```

2021-11-23 12:27 UTC, RPSMain commented
@TAG-Epic all the changes you wanted should be done now

2021-11-23 12:39 UTC, merged