Documenting that guild.chunk returns a list of members
nextcord/nextcord pull request #316
Opened 2021-12-29 16:10 UTC by Scrumpyy

## Summary

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2021-12-29 16:14 UTC, vcokltfre requested changes
While we're here, the return type of the function should be changed to a list of Members too `-> None` -> `-> List[Member]` (make sure List is imported from typing)

2021-12-29 20:40 UTC, TAG-Epic requested changes
This can also be None?

2021-12-30 10:44 UTC, ooliver1 requested changes

2021-12-30 10:44 UTC, ooliver1 commented on nextcord/guild.py
> +    async def chunk(self, *, cache: bool = True) -> List[Member]:
This also needs to have the return type with optional

2021-12-30 13:20 UTC, ooliver1 requested changes

2021-12-30 13:20 UTC, ooliver1 commented on nextcord/guild.py
> +    async def chunk(self, *, cache: bool = True) -> Optional(List[Member]):
Isn't it Optional[] not Optional()

2021-12-30 15:16 UTC, ooliver1 approved these changes

2021-12-31 01:29 UTC, vcokltfre approved these changes

2021-12-31 01:29 UTC, merged