[User commands] Construct member if possible
nextcord/nextcord pull request #360
Opened 2022-01-21 23:16 UTC by Soheab

## Summary

This PR rewrites `_handle_resolved_user` to construct a `Member` is the data if the data available.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-01-23 15:46 UTC, onerandomusername commented on nextcord/application_command.py
> +        else:
you have an if that returns above, which is essentially a guard clause. That means there's no need to else this section which would make it easier to read.

2022-02-01 17:48 UTC, ooliver1 requested changes

2022-02-01 17:48 UTC, ooliver1 commented on nextcord/application_command.py
> +            return member
```suggestion
        if not guild:
            return self._state.store_user(user_payload)

        if isinstance(guild, int):
            guild = self._state.get_guild(guild)

        member = guild.get_member(int(user_id))

        if not member and "members" in resolved_payload:
            member_payload = list(resolved_payload["members"].values())[0]
            # This is required to construct the Member.
            member_payload["user"] = user_payload
            member = Member(data=member_payload, guild=guild, state=self._state)  # type: ignore
            guild._add_member(member)

        return member
```

2022-02-01 18:11 UTC, ooliver1 approved these changes

2022-02-01 18:11 UTC, merged