Add check for confirming datetime instance.
nextcord/nextcord pull request #423
Opened 2022-02-04 04:52 UTC by Shlol762

## Summary

Just checks if the argument is an instance of `datetime` to prevent confusion.

## Checklist

- [x ] If code changes were made then they have been tested.
    - [  ] I have updated the documentation to reflect the changes.
- [  ] This PR fixes an issue.
- [  ] This PR adds something new (e.g. new method or parameters).
- [  ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [  ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-02-04 05:12 UTC, Skelmis approved these changes
lgtm

2022-02-04 09:54 UTC, vcokltfre requested changes

2022-02-04 09:54 UTC, vcokltfre commented on nextcord/member.py
> +                      *, reason: Optional[str] = None):
This function formatting is inconsistent with other methods in this file, could it be changed to match them please.
```suggestion
    async def timeout(
        self,
        timeout: Union[datetime.datetime, datetime.timedelta],
        *,
        reason: Optional[str] = None,
    ) -> None:
```

2022-03-21 17:16 UTC, ooliver1 commented on nextcord/member.py
> +        .. versionadded:: 2.0
this seems to render odd on the docs 
```suggestion
        """|coro|

        Times out this member.

        .. note::

            This is a more direct method of timing out a member.
            You can also time out members using :meth:`Member.edit`.

        .. versionadded:: 2.0

        Parameters
        -----------
        timeout: Optional[Union[:class:`~datetime.datetime`, :class:`~datetime.timedelta`]]
            The time until the member should not be timed out.
            Set this to None to disable their timeout.
        reason: Optional[:class:`str`]
            The reason for editing this member. Shows up on the audit log.
```

2022-03-21 17:18 UTC, ooliver1 approved these changes

2022-03-21 17:18 UTC, merged