Fix issue #494
nextcord/nextcord pull request #495
Opened 2022-02-23 10:39 UTC by MouseMoosz

closes #494 

## Summary

Change from nextcord.Client to commands.Bot in application commands examples

Yes, it fixes issue #494 

## Checklist

- [ x ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ x ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-02-23 16:41 UTC, DenverCoder1 requested changes

2022-02-23 16:41 UTC, DenverCoder1 commented on examples/application_commands/autocompleted_command.py
> +bot = commands.Bot(command_prefix='!')
In most other examples, the prefix used is `$`

```suggestion
bot = commands.Bot(command_prefix='$')
```

2022-02-23 16:46 UTC, DenverCoder1 commented on examples/application_commands/autocompleted_command.py
> +bot = commands.Bot(command_prefix='!')
When #101 is merged, the prefix can even be left out entirely

2022-02-23 16:49 UTC, DenverCoder1 requested changes

2022-02-23 16:49 UTC, DenverCoder1 commented on examples/application_commands/autocompleted_command.py
>  import nextcord
This is an used import
```suggestion
```

2022-02-23 16:49 UTC, DenverCoder1 commented on examples/application_commands/slash_command.py
>  import nextcord
unused import
```suggestion
```

2022-02-23 16:57 UTC, DenverCoder1 commented
Instead of "Fix issue" in the title, it would be better if you could change that to something like "Change nextcord.Client to commands.Bot in examples"

2022-02-23 19:34 UTC, DenverCoder1 requested changes

2022-02-23 19:34 UTC, DenverCoder1 commented on examples/application_commands/autocompleted_command.py
> +bot = commands.Bot(command_prefix='$')
```suggestion
bot = commands.Bot(command_prefix="$")
```

2022-02-23 19:34 UTC, DenverCoder1 commented on examples/application_commands/context_menus.py
> +bot = commands.Bot(command_prefix='!')
```suggestion
bot = commands.Bot(command_prefix="$")
```

2022-02-23 19:34 UTC, DenverCoder1 commented on examples/application_commands/slash_command.py
> +bot = commands.Bot(command_prefix='!')
```suggestion
bot = commands.Bot(command_prefix="$")
```

2022-02-23 19:34 UTC, DenverCoder1 commented on examples/application_commands/sub_commands.py
> +bot = commands.Bot(command_prefix='!')
```suggestion
bot = commands.Bot(command_prefix="$")
```

2022-02-24 06:01 UTC, DenverCoder1 approved these changes
I approve of this change.

In my opinion, all examples should use `commands.Bot` instead of `nextcord.Client` since `commands.Bot` supports many features that every bot should be taking advantage of and it is confusing for beginners to have `commands.Bot` in one place and `nextcord.Client` in another (I have seen many people make the mistake of adding both to their code when really only `commands.Bot` necessary).

After the PR for adding a default command_prefix is merged, I think it might make sense to remove the command_prefix from these examples.

2022-02-24 06:11 UTC, MaskDuck approved these changes
gud job; through you dont need to open a issue thru

2022-02-24 06:15 UTC, MouseMoosz commented
@DenverCoder1

Agreed, a newcomer might get confused by the use of two diffrent methods.

> After the PR for adding a default command_prefix is merged, I think it might make sense to remove the command_prefix from these examples.

I tried to do that in the ones which didn't need a prefix like slash command examples, but command_prefix is a required parm for initialization of the bot.

2022-02-24 06:18 UTC, MouseMoosz commented
> gud job; through you dont need to open a issue thru

Thank you!
I am new to contributing to other projects and in a guide I saw that you should make issues for pull request first, this was not a big pr so yea it would have made more sense to just directly send a pr.

2022-02-24 06:27 UTC, DenverCoder1 commented
Opening issues is a good idea, especially since it allows people to discuss the change before the code is actually written. Some repos even requiring PRs to be related to issues, but in others it's fine to directly open a PR.

> I tried to do that in the ones which didn't need a prefix like slash command examples, but command_prefix is a required parm for initialization of the bot.

Right now it is required to specify command_prefix, but #101 is open to change that.

2022-02-24 06:41 UTC, MouseMoosz commented
> Opening issues is a good idea, especially since it allows people to discuss the change before the code is actually written. Some repos even requiring PRs to be related to issues, but in others it's fine to directly open a PR.
> 
> > I tried to do that in the ones which didn't need a prefix like slash command examples, but command_prefix is a required parm for initialization of the bot.
> 
> Right now it is required to specify command_prefix, but #101 is open to change that.

Alright!

That would be a nice change.

2022-02-28 16:02 UTC, Skelmis approved these changes
lgtm

2022-02-28 17:10 UTC, ooliver1 approved these changes

2022-03-02 14:18 UTC, koala9712 commented on examples/application_commands/sub_commands.py
>  import nextcord
`from nextcord import Interaction` could be used, for consistency across examples

2022-03-04 17:30 UTC, merged