Make SlashOption extend typing.Any
nextcord/nextcord pull request #500
Opened 2022-02-25 15:08 UTC by abrahammurciano

Currently static type checkers will complain that a SlashOption object is not a valid default parameter for a parameter of type `int`, `str`, or anything. E.g.

```py
@nextcord.slash_command(description="bla bla bla")
async def foo(
	self,
	interaction: nextcord.Interaction,
	bar: str = SlashOption(description="bla bla bla"), # SlashOption is not a valid default for parameter of type str
):
	pass
```

## Summary

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-02-25 15:09 UTC, abrahammurciano commented
@DenverCoder1 FYI

2022-02-25 15:12 UTC, alentoghostflame approved these changes
As long as you made sure it still functions, I say it's good :+1: 
Edit: Actually wait why are the checks failing?

2022-02-25 15:13 UTC, DenverCoder1 approved these changes

2022-02-25 15:19 UTC, alentoghostflame requested changes

2022-02-25 15:19 UTC, alentoghostflame commented on nextcord/application_command.py
> +class SlashOption(Any):
This is breaking autodocs for some reason. We need to either find an alternative workaround for typing, or a way to have autodocs ignore this.

2022-02-25 15:40 UTC, DenverCoder1 requested changes
Getting this error when importing the module (Python 3.10)

```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    import nextcord
  File "nextcord/__init__.py", line 24, in <module>
    from .client import *
  File "nextcord/client.py", line 54, in <module>
    from .application_command import message_command, slash_command, user_command
  File "nextcord/application_command.py", line 100, in <module>
    class SlashOption(Any):
  File "/usr/lib/python3.10/typing.py", line 377, in __mro_entries__
    raise TypeError(f"Cannot subclass {self!r}")
TypeError: Cannot subclass typing.Any
```

2022-02-25 16:35 UTC, DenverCoder1 commented
Suggestion to fix:

```py
if TYPE_CHECKING:
    Base = Any
else:
    Base = object

...

class SlashOption(Base):
```

See: https://stackoverflow.com/a/68194494/11608064

2022-02-27 01:44 UTC, DenverCoder1 requested changes

2022-02-27 01:44 UTC, DenverCoder1 commented on nextcord/application_command.py
> +    TYPE_CHECKING,
TYPE_CHECKING was already imported, other than that, looks good

```suggestion
```

2022-02-27 15:34 UTC, MaskDuck approved these changes
lgtm, hasnt test yet

2022-02-27 16:17 UTC, DenverCoder1 approved these changes
Looks good

2022-02-27 16:18 UTC, merged