Update Application Checks Documents
nextcord/nextcord pull request #538
Opened 2022-03-19 10:33 UTC by EyadLordXxXxX

## Summary

This PR updates nextcord.ext.application_checks's documentations to be better/get fixed

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2022-03-19 10:46 UTC, MaskDuck requested changes
what is the purpose of the examples?

2022-03-19 10:58 UTC, Skelmis commented
To, show an example usage? ext.commands show some example usages

2022-03-19 11:19 UTC, EyadLordXxXxX commented
> what is the purpose of the examples?

It's supposed to show examples in the documentation, for example: ext.commands and ext.tasks have examples, ...

2022-03-20 02:43 UTC, DenverCoder1 approved these changes

2022-03-20 03:36 UTC, DenverCoder1 requested changes

2022-03-20 03:36 UTC, DenverCoder1 commented on nextcord/ext/application_checks/core.py
> +            await interaction.response.send_message('You are cool indeed')
Change message?
```suggestion
            await interaction.response.send_message('I have a required role!')
```

2022-03-20 08:47 UTC, ooliver1 commented on nextcord/ext/application_checks/core.py
> +        async def cool(interaction: Interaction):
```suggestion
        async def hasrole(interaction: Interaction):
```

2022-03-20 08:50 UTC, ooliver1 approved these changes

2022-03-20 08:50 UTC, merged