Remove Store channel functionality
nextcord/nextcord pull request #560
Opened 2022-03-29 18:35 UTC by H4ckerxx44

## Summary
Discord [discontinued](https://discord.com/developers/docs/game-and-server-management/special-channels#store-channels) selling games with Store channels a while ago so I figured we remove it.

Might be considered a `breaking change`.

## Checklist

- [X] If code changes were made then they have been tested.
    - [X] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-03-29 18:44 UTC, ooliver1 reviewed
as this is a breaking change (since 1.7), may i suggest editing migrating_2.rst to mention its removal even though its unusable

2022-03-29 20:00 UTC, ooliver1 approved these changes

2022-03-30 17:28 UTC, H4ckerxx44 commented
> Would it also be useful to remove [the enum for store channel](https://github.com/nextcord/nextcord/blob/6ac4187ee86310b5a2ea9d467a4908ed0c95d679/nextcord/enums.py#L188) and similar?

[That would definitely make sense.](https://nextcord.readthedocs.io/en/stable/api.html?highlight=channel%20type#nextcord.ChannelType.store)

2022-03-31 12:24 UTC, ooliver1 requested changes
may be annoying but migrating_2 could do with those appinfo attr changes and the enum change

2022-03-31 18:09 UTC, ooliver1 approved these changes

2022-04-07 19:36 UTC, merged