Fixed everything with flake8 and fix error (player.py)
nextcord/nextcord pull request #57
Opened 2021-08-29 19:51 UTC by kutuzovrusss

## Summary

Fix error (player.py)
Fixed everything with flake8

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-08-29 19:58 UTC, H4ckerxx44 approved these changes
LGTM

2021-08-29 21:46 UTC, Sheepposu approved these changes
Looks good 👍

2021-08-29 23:56 UTC, ooliver1 commented
Just wondering, many of those commits just add an extra line between functions and an extra space in comments

2021-08-30 07:21 UTC, TAG-Epic requested changes
A few things that should be reverted, although it looks pretty good. We should probably wait until the slash commands fork is finished with merging this so theres not so many merge conflicts.

2021-08-30 07:21 UTC, TAG-Epic commented on nextcord/enums.py
> +    guild_update = 1
This should not be formatted.

2021-08-30 07:21 UTC, TAG-Epic commented on nextcord/enums.py
> +            AuditLogAction.channel_update: AuditLogActionCategory.update,
Same here

2021-08-30 07:21 UTC, TAG-Epic commented on nextcord/gateway.py
> +    DISPATCH = 0
This should not be formatted

2021-08-30 07:21 UTC, TAG-Epic commented on nextcord/opus.py
> +APPLICATION_AUDIO = 2049
This should not be formatted

2021-08-30 07:21 UTC, TAG-Epic commented on nextcord/opus.py
> +# Some constants from opus_defines.h
Why was this changed?

2021-08-30 07:21 UTC, TAG-Epic commented on nextcord/player.py
> +        self._stdin: Optional[IO[bytes]] = None
Why was this changed?

2021-08-30 07:21 UTC, TAG-Epic commented on setup.py
> +    description='A Python wrapper for the Discord API forked from discord.py',
What does this change? From 8 spaces to 4 or?

2021-08-30 09:43 UTC, ooliver1 commented on nextcord/player.py
> +        self._stdin: Optional[IO[bytes]] = None
^ this breaks the typehint

2021-09-04 12:01 UTC, ooliver1 commented
Ok back to this PR, could you revert those unnecessary formatting changes, the indent changes and removing "##" to "#" means it's not a title but a subheading which isn't intended

2021-09-10 07:47 UTC, Cheesecake-dev approved these changes

2021-10-03 12:42 UTC, closed without merging