feat: Add a way to see all permissions required to run a given Command
nextcord/nextcord pull request #618
Opened 2022-04-24 11:52 UTC by Skelmis

## Summary

This adds the ability to view the permissions required to run a command. 

As an implementation detail, this method also ensures the immutability of the decorator, ensuring the permissions output stays in line with the required permissions despite runtime changes. 

It would have been nice to avoid setting the attribute each time the check runs, however, due to how the checks work internally it appears you cannot triple nest decorator functions to get that functionality. If you are aware of a way to do this, please comment with a worked nextcord example.

Closes #511 

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

## Testing

These tests show both the usage and the built-in immutability of this approach. Such that even after 'removing' the permissions, they are still set correctly on the next invocation.
```python
import os

from nextcord.ext import commands
from nextcord.ext.commands import Context

bot = commands.Bot(command_prefix="$")

@bot.command()
@commands.has_permissions(manage_guild=True)
async def ping(ctx: Context):
    await ctx.send(str(ctx.command.required_permissions))
    ctx.command.callback.required_permissions = {}
    await ctx.send(str(ctx.command.required_permissions))

@bot.command()
@commands.has_guild_permissions(manage_guild=True)
async def ping_2(ctx: Context):
    await ctx.send(str(ctx.command.required_guild_permissions))
    ctx.command.callback.required_guild_permissions = {}
    await ctx.send(str(ctx.command.required_guild_permissions))

@bot.command()
@commands.bot_has_permissions(manage_guild=True)
async def ping_3(ctx: Context):
    await ctx.send(str(ctx.command.required_bot_permissions))
    ctx.command.callback.required_bot_permissions = {}
    await ctx.send(str(ctx.command.required_bot_permissions))

@bot.command()
@commands.bot_has_guild_permissions(manage_guild=True)
async def ping_4(ctx: Context):
    await ctx.send(str(ctx.command.required_bot_guild_permissions))
    ctx.command.callback.required_bot_guild_permissions = {}
    await ctx.send(str(ctx.command.required_bot_guild_permissions))

bot.run(os.environ["TOKEN"])
```
![image](https://user-images.githubusercontent.com/47520067/164974981-edf05cbb-f56e-4c0b-80c7-bd65d0e19b81.png)
![image](https://user-images.githubusercontent.com/47520067/164974988-cb9be975-938d-4ccb-a0c8-97a9b1ed844d.png)

2022-04-29 19:50 UTC, ooliver1 requested changes

2022-04-29 19:50 UTC, ooliver1 commented on nextcord/ext/commands/core.py
> +        """
style comment: consistency and PEP257 - brief description on the same line as the opening `"""`

2022-04-29 19:50 UTC, ooliver1 commented on nextcord/ext/commands/core.py
> +        dict
```suggestion
        Dict[:class:`str`, :class:`bool`]
```
for specificity in docs

2022-04-29 19:50 UTC, ooliver1 commented
and ^ for all 4 of course

2022-05-08 11:59 UTC, ooliver1 approved these changes

2022-05-20 16:01 UTC, ooliver1 approved these changes

2022-05-20 16:07 UTC, ooliver1 commented
![image](https://user-images.githubusercontent.com/34910574/169568150-f0b302e3-9efa-4987-b127-b79869f254e6.png)
there seems to be some conflicts, im getting ` ! [rejected]          refs/pull/618/head -> fix/511  (non-fast-forward)` and unable to edit in github so I assume you did not enable `allow maintainers to make modifications`, either enable that or resolve conflicts

2022-05-21 02:24 UTC, Skelmis commented
That darn black pr haha, however you have access now. I will resolve it regardless

2022-05-21 02:29 UTC, Skelmis commented
Not sure what you want me to do about pyright, outside of just type ignoring them

2022-05-21 04:37 UTC, Skelmis commented
TODO: Also add this to application checks

2022-06-23 14:45 UTC, ooliver1 commented
> Not sure what you want me to do about pyright, outside of just type ignoring them

you could just conditionally set `if ctx.command is not None`

2022-07-09 16:12 UTC, closed without merging

2023-02-12 14:58 UTC, Soheab commented
Why was this closed?