feat(Embed): return the new embed at `Embed.clear_cields()`
nextcord/nextcord pull request #626
Opened 2022-04-27 10:33 UTC by MaskDuck

## Summary

close #624

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-04-27 11:13 UTC, koala9712 commented
Doc can be updated to show return type.

2022-04-27 15:50 UTC, DenverCoder1 requested changes
Might as well do the same for `remove_field`?

2022-04-27 15:52 UTC, DenverCoder1 commented on nextcord/embeds.py
> +    def clear_fields(self) -> Embed:
For consistency

```suggestion
    def clear_fields(self: E) -> E:
```

2022-04-28 14:42 UTC, DenverCoder1 commented on nextcord/embeds.py
> +            This method returns ``self``
I actually might change my mind about the versionchanged. Since it's not a breaking change, I don't know if it's necessary.
```suggestion
```

2022-04-28 16:12 UTC, DenverCoder1 commented on nextcord/embeds.py
> +        chaining.
Small typo missing end quotes.

```suggestion
        chaining.
        """
```

Also, `remove_field` could return self as well maybe?

2022-04-29 20:11 UTC, ooliver1 reviewed
what happened to the return type

2022-04-29 20:30 UTC, DenverCoder1 commented
> what happened to the return type

All of the existing methods in this lib that follow the builder design pattern seem to just have a comment saying:

"This function returns the class instance to allow for fluent-style chaining."

and they are not documented with "Returns".

2022-04-29 21:02 UTC, ooliver1 commented
oh i see i see

2022-04-29 21:02 UTC, ooliver1 approved these changes

2022-04-29 21:03 UTC, merged