Refactor `examples` folder
nextcord/nextcord pull request #643
Opened 2022-05-13 17:44 UTC by codeman1o1

## Summary

This PR refactors files in the `example` folder.
The following tools were used:
- Pylint
- Flake8
- Black
- Sourcery

Only the `examples` folder has been refactored, so that is why the documentation checkmark isn't checked
I did not run `task pyright` because I have `pylance` and `VS Code` so that is why it isn't checked

## Checklist

- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-05-13 17:50 UTC, ooliver1 commented
please could you sort out the conflicts? black and isort should have already been used on the examples due to #627 
![image](https://user-images.githubusercontent.com/34910574/168339916-8879108c-3d09-4ff3-a63f-4ff78414d426.png)

2022-05-13 18:31 UTC, codeman1o1 commented
That commit should hopefully fix some conflicts

2022-05-13 21:54 UTC, DenverCoder1 commented
A lot of these single quotes changed were apostrophes in comments and docstrings, which should not have been changed to double quotes.

2022-05-14 12:38 UTC, codeman1o1 commented
I reverted back to 14726d8371f9360dd15a06d75bff3a75c3db9df5

2022-05-14 12:53 UTC, codeman1o1 commented
Am I now good to go to resolve the conflicts?

2022-06-16 08:20 UTC, ooliver1 commented on examples/guessing_game.py
> +        await ctx.send('"uess a number between 1 and 10.")
```suggestion
        await ctx.send("Guess a number between 1 and 10.")
```#my bad

2022-06-16 08:22 UTC, ooliver1 commented on examples/guessing_game.py
> +```#my bad
```suggestion
        await ctx.send("Guess a number between 1 and 10.")
```
what the fuck github

2022-06-19 20:07 UTC, Skelmis approved these changes

2022-06-19 21:00 UTC, teaishealthy requested changes

2022-06-19 21:11 UTC, teaishealthy approved these changes

2022-06-19 21:28 UTC, ooliver1 approved these changes

2022-06-19 21:30 UTC, merged