Community/apiv10
nextcord/nextcord pull request #647
Opened 2022-05-16 18:24 UTC by ooliver1

## Summary

Switches nextcord to use discord api v10 and fixes the [relevant changes](https://discord.com/developers/docs/change-log#api-v10)
in order of changelog
- not used
- not used
- added intent
- changed for kick
- resolved
- was removed in #560
- unused
- unused

closes #467

## Checklist

- [ ] If code changes were made then they have been tested.  - needs testing
  - [x] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-05-16 18:28 UTC, ooliver1 commented
needs rough testing
- message content intent
- message embeds
- kick with reason

2022-05-22 09:21 UTC, Soheab commented
Assuming this is going to get merged before the intent deadline, i think there should be an easy way for users to switch back to v9 (like users that can't enable the intent on the portal for unknown reasons). This can be achieved with a global var and a variable users can set I think, something like `discord.http.API_VERSION = 9`.

2022-05-22 09:24 UTC, TAG-Epic commented
> Assuming this is going to get merged before the intent deadline, i think there should be an easy way for users to switch back to v9 (like users that can't enable the intent on the portal for unknown reasons). This can be achieved with a global var and a variable users can set I think, something like `discord.http.API_VERSION = 9`.
> 
> Other than that, looks good to me.

Message content intent still applies on v9.

2022-05-22 09:26 UTC, Soheab commented
> Message content intent still applies on v9.

That is true but it's not enforced there (yet?) aka users don't need to enable it on the portal and in code.

2022-05-22 09:28 UTC, ooliver1 commented
> > Assuming this is going to get merged before the intent deadline, i think there should be an easy way for users to switch back to v9 (like users that can't enable the intent on the portal for unknown reasons). This can be achieved with a global var and a variable users can set I think, something like `discord.http.API_VERSION = 9`.
> > Other than that, looks good to me.
> 
> Message content intent still applies on v9.

Well yeah, but not until August, it applies on v10 fully

2022-06-01 15:43 UTC, ooliver1 commented
> Assuming this is going to get merged before the intent deadline, i think there should be an easy way for users to switch back to v9 (like users that can't enable the intent on the portal for unknown reasons). This can be achieved with a global var and a variable users can set I think, something like `discord.http.API_VERSION = 9`.
> 
> Other than that, looks good to me.

@Soheab how does https://github.com/nextcord/nextcord/pull/647/files#diff-517d49605d29d0371ebe85c47db30b46a9d5a2b12623eac744ab66d4655f2ed3R116-R128 look

2022-06-02 11:58 UTC, Skelmis requested changes

2022-06-02 11:58 UTC, Skelmis commented on docs/migrating_2.rst
> +If you are unable to get the message content intent and would like some time to migrate to application commands:
If you are unable to get the message content intent and would like some time to migrate to application commands you can downgrade the API back to version 9 as shown below.

2022-06-02 12:03 UTC, Skelmis approved these changes

2022-06-02 12:04 UTC, merged