feat: Add a message content intent warning when use ext.commands
nextcord/nextcord pull request #671
Opened 2022-06-09 23:56 UTC by DenverCoder1

## Summary

Since `commands.Bot` is for the ext commands framework which, for the most part, requires message content to work, there can be a warning on startup if `intents.message_content` is not enabled.

This only applies when creating a bot with `commands.Bot` and the `command_prefix` is not an empty iterable or `commands.when_mentioned` since if there's no prefix, there are obviously no commands to listen for and if it is `when_mentioned`, the bot will receive the message content since it will always be mentioned in the messages.

One issue is that DM commands still work without message content intent and it's hard to know if they intend to only have commands work in DMs or not. In this rare case, the user can disable the warning using:

```py
import warnings

warnings.simplefilter("ignore", category=commands.MissingMessageContentIntentWarning)
```

## Screenshot

![image](https://user-images.githubusercontent.com/20955511/172963243-75687807-87e8-4b81-8b7b-67c5a9909d7c.png)

## Non-compliant code

```py
# command prefix is specified, but no intents are enabled
bot = commands.Bot(command_prefix="$")
```
```py
# command prefix is specified, but message_content is not enabled
intents = nextcord.Intents.default()
bot = commands.Bot(command_prefix="$", intents=intents)
```

## Compliant code

```py
# message content is explicitly enabled
intents = nextcord.Intents.default()
intents.message_content = True
bot = commands.Bot(command_prefix="$", intents=intents)
```
```py
# all intents are enabled
intents = nextcord.Intents.all()
bot = commands.Bot(command_prefix="$", intents=intents)
```
```py
# no command prefixes
bot = commands.Bot()
```
```py
# only responds when mentioned
bot = commands.Bot(command_prefix=commands.when_mentioned)
```

## Checklist

- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
  - [x] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-06-10 03:34 UTC, MaskDuck commented
well if i didnt see this pr and i know about it, how can i know how to shut it up? maybe add a small paragraph in the docs?

2022-06-10 19:18 UTC, ooliver1 requested changes

2022-06-10 19:18 UTC, ooliver1 commented on nextcord/ext/commands/bot.py
> +        warnings.simplefilter('ignore', commands.MissingMessageContentIntentWarning)
```suggestion
        warnings.simplefilter("ignore", commands.MissingMessageContentIntentWarning)
```

2022-06-10 20:13 UTC, ooliver1 approved these changes

2022-06-13 18:41 UTC, Skelmis approved these changes
Untested, LGTM

2022-06-16 21:26 UTC, merged