fix(gateway): remove the `$` prefix
nextcord/nextcord pull request #687
Opened 2022-06-17 03:18 UTC by MaskDuck

## Summary

https://github.com/discord/discord-api-docs/pull/5067
## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-06-17 04:00 UTC, DenverCoder1 approved these changes
Looks good, I haven't tested

2022-06-18 03:47 UTC, Skelmis requested changes
The discord change you linked modifies 3 fields, you've changed 5. Care to explain?

2022-06-18 05:03 UTC, MaskDuck commented
@Skelmis 
![image](https://user-images.githubusercontent.com/70831061/174423583-d86b597d-6b2a-42d0-aaef-df82d38224a7.png)

2022-06-18 05:04 UTC, MaskDuck commented
or should i remove two of them too?

2022-06-18 05:04 UTC, Skelmis commented
And..?

Can you provide some links as to where it said those fields also required changing, I can't find them.

2022-06-18 05:18 UTC, MaskDuck commented
i think we have to remove them since...
https://github.com/discord/discord-api-docs/search?q=referrer&type=code
https://github.com/discord/discord-api-docs/search?q=referring_domain&type=code

both of those returns None.

2022-06-19 04:01 UTC, DenverCoder1 approved these changes
:+1: Should be fine to remove referrer stuff, as mentioned it doesn't appear in the docs. Only references I could find were in discord.py and DiscordPHP. I checked Discord.js and it seems to not have them.

2022-06-19 04:01 UTC, DenverCoder1 commented on nextcord/gateway.py
> +                "properties": {"os": sys.platform, "browser": "nextcord", "device": "nextcord"},
I'd recommend to keep the comma after the device name so it displays on separate lines

```suggestion
                "properties": {
                    "os": sys.platform,
                    "browser": "nextcord",
                    "device": "nextcord",
                },
```

2022-06-19 19:06 UTC, Skelmis approved these changes

2022-06-19 20:50 UTC, ooliver1 approved these changes

2022-06-19 20:52 UTC, merged