feat: add remove_modal
nextcord/nextcord pull request #707
Opened 2022-06-26 07:32 UTC by MaskDuck

## Summary

the reason to implement remove_modal is the same reason we should implement remove_view ig

## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-06-26 07:33 UTC, MaskDuck commented on nextcord/client.py
> +            The view to register for dispatching.
```suggestion
            The view to remove from dispatching.
```

2022-06-26 08:04 UTC, DenverCoder1 commented on nextcord/client.py
> +            The view to remove from dispatching.
```suggestion
            The modal to remove from dispatching.
```

2022-06-26 15:37 UTC, ooliver1 requested changes

2022-06-26 15:37 UTC, ooliver1 commented on nextcord/client.py
> +        ------------
```suggestion
        Parameters
        ----------
```

2022-06-26 15:37 UTC, ooliver1 commented on nextcord/client.py
> +        -------
```suggestion
        Raises
        ------
```

2022-07-30 11:16 UTC, koala9712 commented
1) Why is this still a draft
2) Please update original comment with appropriate checks in the checklist
3) Testing code?

2022-07-31 14:37 UTC, ooliver1 commented
https://github.com/nextcord/nextcord/pull/706#issuecomment-1200438016

2022-07-31 14:37 UTC, closed without merging