feat: use app_permissions from Discord
nextcord/nextcord pull request #721
Opened 2022-06-29 19:45 UTC by EmreTech

## Summary

This uses the newly added `app_permissions` field for the permissions property in Interactions. Closes #720.

## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-06-29 19:59 UTC, DenverCoder1 commented on nextcord/interactions.py
> +            self._app_permissions = int(data.get("app_permissions"))  # type: ignore
I think self.guild check can be removed as well and just have
`data.get("app_permissions", 0)`

The property could also stay as `_permissions` I think to reduce the PR noise (fewer changes)

2022-06-29 20:17 UTC, ooliver1 requested changes

2022-06-29 20:19 UTC, ooliver1 commented on nextcord/interactions.py
>          self.user: Optional[Union[User, Member]] = None
```diff
         self.user: Optional[Union[User, Member]] = None
-        self._permissions: int = 0
-
-        # TODO: there's a potential data loss here
-        if self.guild_id:
-            guild = self.guild or Object(id=self.guild_id)
-            try:
-                member = data["member"]
-            except KeyError:
-                pass
-            else:
-                self.user = Member(state=self._state, guild=guild, data=member)  # type: ignore
-                self._permissions = int(member.get("permissions", 0))
-        else:
-            try:
-                self.user = User(state=self._state, data=data["user"])
-            except KeyError:
-                pass
+        self._permissions: int = int(data.get("app_permissions", 0))
```

2022-06-29 20:21 UTC, EmreTech commented on nextcord/interactions.py
>          self.user: Optional[Union[User, Member]] = None
Ah right

2022-06-29 20:23 UTC, EmreTech commented
> So it looks like `permissions` is permissions for the _user_ and `app_permissions` is permissions for the _bot_, so `permissions` probably shouldn't be touched at all.

Oh I thought `permissions` was for the bot
My bad

2022-07-01 02:10 UTC, DenverCoder1 approved these changes
Looks good, tested.

2022-07-01 02:11 UTC, DenverCoder1 commented on nextcord/interactions.py
> +        """:class:`Permissions` The resolved permissions of the bot in the channel, including overwrites
```suggestion
        """:class:`Permissions`: The resolved permissions of the bot in the channel, including overwrites
```

2022-07-01 17:27 UTC, ooliver1 requested changes

2022-07-01 17:27 UTC, ooliver1 commented on nextcord/interactions.py
> +        """:class:`Permissions`: The resolved permissions of the member in the channel, including overwrites
confused as to why the dot was removed, its in almost every other docstring

2022-07-01 17:36 UTC, ooliver1 approved these changes

2022-07-01 17:39 UTC, merged

2022-07-01 17:50 UTC, DenverCoder1 commented
What happened to the colon after Permissions?