docs(version_guarantees): add minor may break
nextcord/nextcord pull request #738
Opened 2022-07-09 16:58 UTC by ooliver1

## Summary

Minor version bumps can actually contain breaking changes, this lists in the guarantees that this may be the case.

## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2022-07-09 16:59 UTC, Skelmis requested changes

2022-07-09 16:59 UTC, Skelmis commented on docs/version_guarantees.rst
> +Nextcord does not follow semantic versioning exactly, The main difference is that breaking changes may also be made on minor version bumps (similar to Python's scheme).
Lowercase the `t`

2022-07-09 17:02 UTC, Skelmis approved these changes

2022-07-09 20:48 UTC, EmreTech approved these changes

2022-07-09 21:33 UTC, TAG-Epic commented
Semver should be followed.

2022-07-10 05:40 UTC, EmreTech commented
> Semver should be followed.

Okay then. Get Discord to somewhat follow Semver with their API, then we'll talk.

2022-07-10 17:44 UTC, ooliver1 commented
> Semver should be followed.

This change is so we are not limited to changing the major version every time there is a breaking change on Discord's API - which is pretty common. This reflects how discord.py actually handled such as [discord.py v1.5.0](https://discordpy.readthedocs.io/en/latest/whats_new.html#v1-5-0) when gateway intents were released.

2022-07-11 14:30 UTC, DenverCoder1 approved these changes
Sounds good to me.

(Using actual semver, the main repo would be on v4 before nc v3 is released 😃)

2022-07-11 16:16 UTC, ooliver1 commented
> > Sounds good to me.
> > (Using actual semver, the main repo would be on v4 before nc v3 is released 😃)
> 
> Yeah this has been a internal topic for a while now, I dont want to block NCv2 from bumping the major version due to bad naming.

I don’t know what internal conversations this is about, because I don't think it's involved anyone.

2022-07-17 20:22 UTC, ooliver1 commented
> Sounds good to me.
> 
> (Using actual semver, the main repo would be on v4 before nc v3 is released smiley)
> 
> **Updated with discussion from Discord**
> 
> If it's a breaking change that will affect very few users I don't think it needs a major release.
> 
> For something that many people would need to fix, a major would make sense.
> 
> One thing that's common for dependencies is a locked major version (eg. `nextcord>=2.0.0,<3`). That way the code is less likely to break from automatic dependency updates. So that's one reason to make all breaking changes major releases.
> 
> Some "breaking changes" are a bit of a stretch though and require making up an unlikely scenario, and for those, a major version change is not needed in my opinion.
> 
> Tbh it's not critical to go one way or the other as long as changes are clearly documented in the release notes.

Good words on the updates, we will go with that thank you. Time will see on what changes will require a major and what is a stretch.

2022-07-17 20:22 UTC, merged