feat: remove_view & remove_modal
nextcord/nextcord pull request #820
Opened 2022-09-19 04:58 UTC by EmreTech

## Summary

This implements `remove_view` and `remove_modal` in `nextcord.Client` and `nextcord.ConnectionState`. Closes #425.

## Checklist

- [ ] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-09-19 15:09 UTC, ooliver1 requested changes

2022-09-19 15:09 UTC, ooliver1 commented on nextcord/client.py
> +        ------------
Unnecessary heading underlining.
```suggestion
        Parameters
        ----------
```

2022-09-19 15:09 UTC, ooliver1 commented on nextcord/client.py
> +        -------
```suggestion
        Raises
        ------
```

2022-09-19 15:09 UTC, ooliver1 commented on nextcord/client.py
> +        ------------
```suggestion
        Parameters
        ----------
```

2022-09-19 15:09 UTC, ooliver1 commented on nextcord/client.py
> +        -------
```suggestion
        Raises
        ------
```

2022-10-01 13:31 UTC, Skelmis requested changes
Sadly the view store implements `add_view` and `remove_view` in different ways

``add_view`` stores views under the key ``(item.type.value, message_id, item.custom_id)`` while ``remove_view`` attempts to pop the key ``(item.type.value, item.custom_id)``, which don't line up. This is not your fault, however, requires fixing for this PR to actually work based on my tests.

I do not have a suitable fix for this at time of review. This should likely become a thread in bikeshedding as it requires further investigation + debugging with live data I don't have on hand right now.
Note: I will open the thread myself so I can add debug data

2022-10-02 03:58 UTC, Skelmis approved these changes
[Tested](https://nexttest.koldfusion.xyz/nextcord/820)

2022-10-02 18:31 UTC, DenverCoder1 commented on nextcord/client.py
> +            The view to remove from dispatching.
`message_id` parameter is not yet documented

2022-10-03 03:35 UTC, DenverCoder1 reviewed
What happens when a message_id is not passed? If the view is sent in multiple messages, do you need to remove it for each one? What happens if the view wasn't sent in a message?

2022-10-03 03:35 UTC, DenverCoder1 commented on nextcord/client.py
> +            The view to remove from dispatching.
```suggestion
            The modal to remove from dispatching.
```

2022-10-03 04:13 UTC, EmreTech commented
> What happens when a message_id is not passed? If the view is sent in multiple messages, do you need to remove it for each one? What happens if the view wasn't sent in a message?

I don't get what the confusion is about? It should pretty much work the opposite of `add_view`, where by default `message_id` is None.
Can you elaborate why you asked these questions in the first place? I just don't get it.

2022-10-03 04:22 UTC, DenverCoder1 commented
I didn't realize `add_view` took a message_id, but it makes a lot of sense now. I had just always used it without one like in the examples, so I wasn't sure where the `message_id` was coming from.

2022-10-03 04:23 UTC, DenverCoder1 approved these changes

2022-10-07 20:18 UTC, teaishealthy requested changes

2022-10-07 20:18 UTC, teaishealthy commented on nextcord/client.py
> +            raise TypeError(f"Expected an instance of View not {view.__class__!r}")
```suggestion
            raise TypeError(f"Expected an instance of View not {view.__class__.__name__}")
```
This is inconsistent with the rest of the library

2022-10-24 10:47 UTC, ooliver1 approved these changes

2022-10-24 10:48 UTC, merged