Doc/application command error
nextcord/nextcord pull request #826
Opened 2022-10-01 12:52 UTC by Skelmis

## Summary

Adds a note to the documentation inline with the internal implementation.

## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-10-01 14:45 UTC, ooliver1 approved these changes

2022-10-01 14:46 UTC, ooliver1 requested changes
Accidental approval :sweat_smile:
![error with documentation changes](https://user-images.githubusercontent.com/34910574/193414996-6b763cd8-5a39-4abf-b1d3-750724bcd785.png) (preview found via checks)
The note should likely be above the params so this does not occur.

2022-10-01 15:03 UTC, ooliver1 approved these changes

2022-10-02 02:32 UTC, DenverCoder1 approved these changes

2022-10-02 23:16 UTC, merged