feat: mention total limit
nextcord/nextcord pull request #837
Opened 2022-10-05 14:48 UTC by MaskDuck

## Summary

closes #810 

## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-10-06 13:21 UTC, DenverCoder1 reviewed
Just a couple small documentation suggestions, but otherwise looks good 👍

2022-10-06 13:21 UTC, DenverCoder1 commented on docs/api.rst
> +        This rule checks if the number of mentions in the message is more than the maximum allowed the number of mentions allowed.
The wording here seems a bit repetitive
```suggestion
        This rule checks if the number of mentions in the message is more than the maximum allowed.
```

2022-10-06 13:21 UTC, DenverCoder1 commented on nextcord/auto_moderation.py
> +        The max amount of mentions allowed in one messsage.
```suggestion
    mention_total_limit: Optional[:class:`int`]
        The maximum amount of mentions allowed in a messsage.
```

2022-10-06 15:46 UTC, DenverCoder1 approved these changes
Looks good, I haven't tested

2022-10-07 20:20 UTC, teaishealthy approved these changes

2022-10-10 02:39 UTC, EmreTech approved these changes
Haven't tested

2022-10-24 10:50 UTC, ooliver1 requested changes

2022-10-24 10:50 UTC, ooliver1 commented on docs/api.rst
> +        This rule checks if the number of mentions in the message is more than the maximum allowed.
```suggestion
        This rule checks if the number of mentions in the message is more than the maximum allowed.

        .. versionadded:: 2.3
```

2022-11-04 17:36 UTC, ooliver1 approved these changes
Tested
```py
@bot.slash_command(name="create-rule", dm_permission=False)
async def create_rule(inter: Interaction):
    assert inter.guild is not None

    await inter.guild.create_auto_moderation_rule(
        name="Rule",
        trigger_type=AutoModerationTriggerType.mention_spam,
        trigger_metadata=AutoModerationTriggerMetadata(mention_total_limit=3),
        event_type=AutoModerationEventType.message_send,
        actions=[
            AutoModerationAction(
                type=AutoModerationActionType.send_alert_message,
                metadata=AutoModerationActionMetadata(
                    channel=inter.guild.get_channel(802586580766162967)
                ),
            )
        ],
        enabled=True,
    )
    await inter.send("ok")
```

2022-11-04 17:36 UTC, ooliver1 commented on nextcord/auto_moderation.py
> +
```suggestion

        .. versionadded:: 2.3

```

2022-11-05 20:03 UTC, merged