feat: default_sort_order
nextcord/nextcord pull request #838
Opened 2022-10-08 13:07 UTC by MaskDuck

## Summary

discord/discord-api-docs#5488

## Checklist

- [ ] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-10-08 13:17 UTC, ooliver1 commented
Please can you use the `Checklist` properly

2022-10-08 13:19 UTC, ooliver1 requested changes

2022-10-08 13:19 UTC, ooliver1 commented on nextcord/enums.py
> +class SortOrderTypes(IntEnum):
This does not match any other enum, where it uses a singular instead of plural names, as there cannot be multiple sort orders at once.

2022-10-09 14:15 UTC, ooliver1 requested changes

2022-10-09 14:15 UTC, ooliver1 commented on docs/api.rst
> +.. class:: SortOrderType
```suggestion
.. class:: SortOrderType

    .. versionadded:: 2.3
```

2022-10-09 14:15 UTC, ooliver1 commented on docs/api.rst
> +    The default sort order type used to sort posts in forum channel.
```suggestion
    The default sort order type used to sort posts in a :class:`ForumChannel`.
```

2022-10-09 14:15 UTC, ooliver1 commented on nextcord/channel.py
> +        The default sort order type used to sort posts in forum channels.
```suggestion
        The default sort order type used to sort posts in forum channels.

        .. versionadded:: 2.3
```

2022-10-09 14:15 UTC, ooliver1 commented on nextcord/channel.py
> +            The default sort order type used to sort posts in forum channels.
```suggestion
            The default sort order type used to sort posts in forum channels.

            .. versionadded:: 2.3
```

2022-10-09 14:15 UTC, ooliver1 commented on nextcord/guild.py
> +            The default sort order used to sort posts in this channel.
```suggestion
            The default sort order used to sort posts in this channel.

            .. versionadded:: 2.3
```

2022-10-09 14:45 UTC, teaishealthy approved these changes

2022-10-10 02:41 UTC, EmreTech approved these changes
Besides oliver's suggestions, this looks good

2022-10-24 04:55 UTC, DenverCoder1 approved these changes
Code looks good to me, I just have a grammatical suggestion. (Haven't tested)

2022-10-24 04:55 UTC, DenverCoder1 commented on docs/api.rst
> +        Sort forum posts by its activity.
```suggestion
        Sort forum posts by their activity.
```

2022-10-24 04:55 UTC, DenverCoder1 commented on docs/api.rst
> +        Sort forum posts by its creation date.
```suggestion
        Sort forum posts by their creation date.
```

2022-10-30 17:15 UTC, ooliver1 requested changes
Creating a channel with the default sort order type does not actually work, I am not sure if this is Discord's fault or not but:

```
POST https://discord.com/api/v10/guilds/802586580766162964/channels with {"type":15,"name":"name","permission_overwrites":[],"topic":"topic"} has returned 201
POST https://discord.com/api/v10/guilds/802586580766162964/channels has received {'id': '1036327296447029342', 'last_message_id': None, 'type': 15, 'name': 'name', 'position': 1, 'flags': 0, 'parent_id': None, 'topic': 'topic', 'guild_id': '802586580766162964', 'permission_overwrites': [], 'rate_limit_per_user': 0, 'nsfw': False, 'available_tags': [], 'template': '', 'default_reaction_emoji': None, 'default_sort_order': None}
```
```py
@bot.slash_command(dm_permission=False)
async def create_channel(inter: Interaction):
    assert inter.guild is not None

    await inter.guild.create_forum_channel(
        name="name", topic="topic", default_sort_order=SortOrderType.creation_date
    )
```

2022-10-30 17:15 UTC, ooliver1 commented on nextcord/enums.py
> +class SortOrderType(IntEnum):
`__all__` needs to be modified so it is exposed via the wildcard imports in `__init__.py`

2022-10-30 17:20 UTC, ooliver1 reviewed
`http.py` does not in fact support `default_sort_order` as a valid parameter, so discord never actually receives the value.

https://github.com/MaskDuck/nextcord/blob/78d164b43d5e5bb30fd29b1b1f21ab93067131b3/nextcord/http.py#L1031-L1044

Please test **your own** pull requests.

2022-11-04 18:00 UTC, ooliver1 approved these changes
Tested
```py
@bot.slash_command(name="create-channel", dm_permission=False)
async def create_channel(inter: Interaction):
    assert inter.guild is not None

    await inter.guild.create_forum_channel(
        name="name", topic="topic", default_sort_order=SortOrderType.creation_date
    )
    await inter.send("ok")
```

2022-11-04 18:01 UTC, merged