docs(guild): add DEVELOPER_SUPPORT_SERVER feature
nextcord/nextcord pull request #855
Opened 2022-10-21 18:26 UTC by toolifelesstocode

## Summary

This documents the new `DEVELOPER_SUPPORT_SERVER` guild feature. Implements https://github.com/discord/discord-api-docs/pull/5572

## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2022-10-21 18:42 UTC, ooliver1 requested changes
Could you add it to here too?

https://github.com/nextcord/nextcord/blob/master/nextcord/types/guild.py#L59

2022-10-21 18:50 UTC, toolifelesstocode commented
> Could you add it to here too?
> 
> https://github.com/nextcord/nextcord/blob/a856817de5ceb4c258079f637044f8c60c4f52cf/nextcord/types/guild.py#L59

Added in b49c7baf82dbfda4d04a0b850d27c47a74c7a2fe 🙂

2022-10-22 06:56 UTC, EmreTech approved these changes

2022-10-22 15:31 UTC, ooliver1 approved these changes

2022-10-22 15:32 UTC, ooliver1 approved these changes

2022-10-24 03:51 UTC, DenverCoder1 approved these changes

2022-10-24 10:06 UTC, Skelmis approved these changes

2022-10-24 11:18 UTC, merged