docs: Fix single-backtick words to double-backtick or links
nextcord/nextcord pull request #863
Opened 2022-10-23 06:20 UTC by DenverCoder1

## Summary

Made 100+ fixes to single-backtick words in rst files to double-backtick phrases or reference links depending on the case.

This helps with readability since single-backtick phrases are italicized rather than set in inline-codeblocks. 

A few additional small docs fixes were also made (eg. missing colon, etc.) in certain cases.

## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2022-10-23 08:46 UTC, Skelmis approved these changes

2022-10-24 11:24 UTC, ooliver1 requested changes

2022-10-24 11:24 UTC, ooliver1 commented on nextcord/application_command.py
> +        callback: Optional[:class:`Callable`]
Nearly every other reference to typing.* doesn't use links so the types in the docstrings are shorter.

2022-10-24 11:24 UTC, ooliver1 commented on nextcord/application_command.py
> +        autocomplete_callback: Optional[:class:`Callable`]
Same as above.

2022-10-27 18:28 UTC, teaishealthy approved these changes

2022-10-28 15:55 UTC, ooliver1 approved these changes

2022-10-28 15:55 UTC, merged