refactor(iterators): correctly type iterators
nextcord/nextcord pull request #872
Opened 2022-10-27 19:04 UTC by teaishealthy

## Summary

Closes #836 

Ref #849, `git checkout master` failed and then I git reset to upstream/master and force pushed :(

## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [x] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-11-06 12:24 UTC, teaishealthy commented
The errors for `set_permissions` are fixed by #869

2022-11-07 22:48 UTC, EmreTech requested changes
This pyright dependency bump seems to be giving out a lot of errors that aren't related to this PR, so you should either move the changes to a new PR or leave the task to someone else.

2022-11-08 00:08 UTC, ooliver1 commented
> This pyright dependency bump seems to be giving out a lot of errors that aren't related to this PR, so you should either move the changes to a new PR or leave the task to someone else.

I'll get onto this now.

2022-11-16 01:00 UTC, EmreTech requested changes

2022-11-16 01:00 UTC, EmreTech commented on nextcord/iterators.py
> +    def __init__(self, guild: Guild, limit: int = 1000, after: Optional[SnowflakeTime] = None):
`limit` supports `None`, as shown by `MemberIterator._get_retrieve`.

2022-11-26 17:59 UTC, EmreTech approved these changes

2022-11-28 20:05 UTC, ooliver1 approved these changes

2022-11-28 20:07 UTC, merged