refactor: alias new files
nextcord/nextcord pull request #885
Opened 2022-11-05 04:17 UTC by MaskDuck

## Summary

title 

btw this has also fixed an typo in alias_license.py

## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2022-11-05 04:34 UTC, EmreTech approved these changes

2022-11-20 08:34 UTC, TAG-Epic requested changes
There is also a big chance voice was broken by this as that has to be fixed manually

2022-11-20 08:34 UTC, TAG-Epic commented on discord/bans.py
> +
This doesnt seem like valid syntax

2022-11-20 13:37 UTC, ooliver1 commented
Please can you actually test your own PRs

2022-11-20 14:22 UTC, DenverCoder1 commented
This PR doesn't fix all of the files.

It probably needs to be run again after updating the base branch.

When this PR was opened, the aliasgen script didn't work and was crashing part-way through because of the issue that was fixed in #888.

2022-11-20 14:52 UTC, closed without merging