feat(automod): regex patterns
nextcord/nextcord pull request #887
Opened 2022-11-05 22:03 UTC by EmreTech

## Summary

This PR adds support for regex patterns in automod trigger metadata. Closes #884.

## Checklist

- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-11-15 22:27 UTC, teaishealthy requested changes

2022-11-15 22:27 UTC, teaishealthy commented on nextcord/auto_moderation.py
> +            the ``re`` module.
```suggestion
            The flavor of regex used is Rust flavor and has no guarantees of working with
            the ``re`` module.
            Each regex pattern must be 75 characters or less.
```

2023-01-03 16:19 UTC, ooliver1 requested changes
![Auto Moderation Rule Create Test](https://cdn.discordapp.com/attachments/802586580766162967/1059868389209804851/image.png) tested.
```py
await inter.guild.create_auto_moderation_rule(
    name="Block everything",
    event_type=AutoModerationEventType.message_send,
    trigger_type=AutoModerationTriggerType.keyword,
    actions=[AutoModerationAction(type=AutoModerationActionType.block_message)],
    trigger_metadata=AutoModerationTriggerMetadata(regex_patterns=["."]),
)
```

2023-01-03 16:19 UTC, ooliver1 commented on nextcord/auto_moderation.py
> +            Each regex pattern must be 75 characters or less.
Versionadded please

2023-01-20 01:19 UTC, EmreTech commented
> 

Should I put this in the warnings section?

2023-01-22 15:08 UTC, ooliver1 commented
![image](https://user-images.githubusercontent.com/34910574/213923136-5d91a8a1-e0f3-4847-9531-0fc1631c5805.png)
I would think just like this

2023-01-22 15:10 UTC, ooliver1 commented on nextcord/auto_moderation.py
> +            the ``re`` module.
```suggestion
            the :mod:`re` module.
```
<https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#role-py-mod>

2023-01-28 00:16 UTC, teaishealthy approved these changes

2023-01-29 20:06 UTC, Skelmis approved these changes

2023-01-30 12:41 UTC, ooliver1 approved these changes

2023-01-30 12:41 UTC, merged