refactor(abc): remove the use of ** for GuildChannel.move
nextcord/nextcord pull request #905
Opened 2022-11-13 17:57 UTC by ooliver1

## Summary

Similar to #695 and #719, this removes the use of `**` catchall options for `abc.GuildChannel.move`.

## Checklist

- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
  - [x] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-11-14 12:33 UTC, teaishealthy commented on nextcord/abc.py
> +        if category not in (MISSING, None):
```suggestion
        if category:
```

2022-11-14 14:02 UTC, ooliver1 commented
Pyright seems to not want to run, closing and opening in hope that this fixes it.

2022-11-22 05:35 UTC, Skelmis approved these changes
untested

2022-11-26 23:43 UTC, teaishealthy requested changes

2022-11-26 23:43 UTC, teaishealthy commented on nextcord/abc.py
> +            d: dict[str, Any] = {"id": channel.id, "position": index}
```suggestion
            d: Dict[str, Any] = {"id": channel.id, "position": index}
```

2023-01-22 17:27 UTC, teaishealthy approved these changes
untested

2023-01-22 17:36 UTC, merged