feat: add create_webhook in forum & voice channels
nextcord/nextcord pull request #914
Opened 2022-11-21 12:08 UTC by I-Wings-I

## Summary

Added In The Create_Webhook For Text Channels To Forums And Voice Channels.

Weirdly on the voice channel, the webhook comes back good and does work, but it doesn't show in the Integration tab when editing the channel.

## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-11-21 14:26 UTC, toolifelesstocode approved these changes

2022-11-21 20:15 UTC, EmreTech requested changes

2022-11-21 20:15 UTC, EmreTech commented on nextcord/channel.py
> +
Missing `..versionadded`

2022-11-21 20:15 UTC, EmreTech commented on nextcord/channel.py
> +
Missing `..versionadded`

2022-11-22 04:13 UTC, EmreTech requested changes

2022-11-22 04:13 UTC, EmreTech commented on nextcord/channel.py
> +        Requires :attr:`~.Permissions.manage_webhooks` permissions.
```suggestion
        Requires :attr:`~.Permissions.manage_webhooks` permissions.

        ..versionadded:: 2.4
```

2022-11-22 04:13 UTC, EmreTech commented on nextcord/channel.py
> +        Requires :attr:`~.Permissions.manage_webhooks` permissions.
```suggestion
        Requires :attr:`~.Permissions.manage_webhooks` permissions.

        ..versionadded:: 2.4
```

2022-11-23 06:27 UTC, EmreTech requested changes

2022-11-23 06:27 UTC, EmreTech commented on nextcord/channel.py
> +        Requires :attr:`~.Permissions.manage_webhooks` permissions.
```suggestion
        Creates a webhook for this channel.

        Requires :attr:`~.Permissions.manage_webhooks` permissions.
```
The description got removed.

2022-11-23 06:27 UTC, EmreTech commented on nextcord/channel.py
> +        Requires :attr:`~.Permissions.manage_webhooks` permissions.
```suggestion
        Creates a webhook for this channel.

        Requires :attr:`~.Permissions.manage_webhooks` permissions.
```

2022-12-02 19:29 UTC, toolifelesstocode approved these changes
(Approving the new changes)

2022-12-05 15:37 UTC, EmreTech commented on nextcord/channel.py
> +        Creates a webhook for this channel.
```suggestion
        """|coro|

        Creates a webhook for this channel.
```

2022-12-05 15:37 UTC, EmreTech commented on nextcord/channel.py
> +        Creates a webhook for this channel.
```suggestion
        """|coro|

        Creates a webhook for this channel.
```

2022-12-05 15:43 UTC, ooliver1 requested changes

2022-12-05 15:43 UTC, ooliver1 commented on nextcord/channel.py
> +        ..versionadded:: 2.4
```suggestion
        .. versionadded:: 2.4
```
![image](https://user-images.githubusercontent.com/34910574/205679459-f8af0ed4-8233-4b85-abe3-3e59ae75a70e.png)
Spacing matters.

2022-12-05 15:43 UTC, ooliver1 commented on nextcord/channel.py
> +        ..versionadded:: 2.4
```suggestion
        .. versionadded:: 2.4
```

2023-01-22 15:13 UTC, ooliver1 approved these changes

2023-01-22 15:13 UTC, merged