docs(guild): add missing features
nextcord/nextcord pull request #916
Opened 2022-11-23 12:53 UTC by MaskDuck

## Summary

This PR documents the guild features `ANIMATED_BANNER`, `APPLICATION_COMMAND_PERMISSIONS_V2`, `INVITE_DISABLED` and `ROLE_ICONS`.

## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2022-11-24 23:08 UTC, ooliver1 requested changes
This is missing `INVITES_DISABLED` and `ROLE_ICONS` as documented [here](https://discord.com/developers/docs/resources/guild#guild-object-guild-features).

2022-12-05 10:47 UTC, Skelmis requested changes

2022-12-07 13:01 UTC, Skelmis requested changes

2022-12-07 13:01 UTC, Skelmis commented on nextcord/types/guild.py
> +    "INVITE_DISABLED",
```suggestion
    "INVITES_DISABLED",
```

2022-12-25 13:13 UTC, ooliver1 commented
But their functions being documented are incorrect now.

2022-12-31 04:49 UTC, EmreTech approved these changes
Double checked with the [Guild Features list](https://discord.com/developers/docs/resources/guild#guild-object-guild-features).

2023-01-03 16:30 UTC, ooliver1 approved these changes

2023-01-03 16:32 UTC, merged