chore: rename license holder to Nextcord Developers
nextcord/nextcord pull request #930
Opened 2022-12-06 18:37 UTC by ooliver1

## Summary

Rename the license holder from `tag-epic` to `Nextcord Developers` to cover the fact that this isn't owned by one person.
<https://canary.discord.com/channels/881118111967883295/881124672056467456/1043505404535128114>
This uses SPDX for headers to reduce repetitive copying.

## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2022-12-07 12:44 UTC, Skelmis requested changes

2022-12-07 12:44 UTC, Skelmis commented on unaliased-setup.py
>      "nextcord.ext.commands",
If we are adding new features to the discord alias, also add `slash_utils`
```suggestion
    "nextcord.ext.commands",
    "nextcord.ext.slash_utils",
```

2022-12-07 18:23 UTC, ArjunSharda approved these changes

2022-12-08 09:28 UTC, EmreTech approved these changes

2022-12-08 12:06 UTC, merged