chore: Change mentions of NSFW to "age restricted"
nextcord/nextcord pull request #939
Opened 2022-12-08 18:32 UTC by Soheab

## Summary

This PR changes almost all mentions of "NSFW" in the docstrings to "age restricted" since discord has done the same for their TOS/Guidelines and in the UI.
 
I'm unsure if we should also change the classes with "NSFW" in the name or at least add them ad aliases if we do.

## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2022-12-09 03:33 UTC, EmreTech requested changes
Few grammar mistakes I noticed.

> I'm unsure if we should also change the classes with "NSFW" in the name or at least add them ad aliases if we do.

As for this, we should definitely add aliases for the old class names because otherwise that would be a breaking change and would be left for 3.0.

2022-12-09 03:33 UTC, EmreTech commented on nextcord/channel.py
> +            To check if the channel or the guild of that channel are marked as age restricted, consider :meth:`is_nsfw` instead.
```suggestion
            To check if the channel or the guild of that channel are age restricted, consider :meth:`is_nsfw` instead.
```

2022-12-09 03:33 UTC, EmreTech commented on nextcord/channel.py
> +            To check if the channel or the guild of that channel are marked as age restricted, consider :meth:`is_nsfw` instead.
```suggestion
            To check if the channel or the guild of that channel are age restricted, consider :meth:`is_nsfw` instead.
```

2022-12-09 03:33 UTC, EmreTech commented on nextcord/channel.py
> +            To check if the channel or the guild of that channel are marked as age restricted, consider :meth:`is_nsfw` instead.
```suggestion
            To check if the channel or the guild of that channel are age restricted, consider :meth:`is_nsfw` instead.
```

2022-12-09 03:33 UTC, EmreTech commented on nextcord/ext/application_checks/core.py
> +    """A :func:`.check` that checks if the channel is a age restricted channel.
```suggestion
    """A :func:`.check` that checks if the channel is age restricted.
```

2022-12-09 03:33 UTC, EmreTech commented on docs/migrating.rst
> +- :func:`~ext.commands.is_nsfw` checks if the channel the command is in is an age restricted channel.
```suggestion
- :func:`~ext.commands.is_nsfw` checks if the channel the command is in is age restricted.
```

2023-01-31 01:40 UTC, Skelmis approved these changes

2023-02-20 06:46 UTC, EmreTech reviewed
Mostly spelling and grammar errors.

2023-02-20 06:46 UTC, EmreTech commented on docs/api.rst
> +        The guild contains age restriced content.
```suggestion
        The guild contains age restricted content.
```

2023-02-20 06:46 UTC, EmreTech commented on docs/api.rst
> +        The guild does not contain any age restriced content.
```suggestion
        The guild does not contain any age restricted content.
```

2023-02-20 06:46 UTC, EmreTech commented on docs/api.rst
> +        The guild may contain age restriced content.
```suggestion
        The guild may contain age restricted content.
```

2023-02-20 06:46 UTC, EmreTech commented on docs/api.rst
> +            Checks if a Age Restriction level is higher than another.
```suggestion
            Checks if an Age Restriction level is higher than another.
```

2023-02-20 06:46 UTC, EmreTech commented on docs/api.rst
> +            Checks if a Age Restriction level is lower than another.
```suggestion
            Checks if an Age Restriction level is lower than another.
```

2023-02-20 06:46 UTC, EmreTech commented on docs/api.rst
> +            Checks if a Age Restriction level is higher or equal to another.
```suggestion
            Checks if an Age Restriction level is higher or equal to another.
```

2023-02-20 06:46 UTC, EmreTech commented on docs/api.rst
> +            Checks if a Age Restriction level is lower or equal to another.
```suggestion
            Checks if an Age Restriction level is lower or equal to another.
```

2023-02-20 06:46 UTC, EmreTech commented on docs/api.rst
> +            Checks if a Age Restriction level is lower or equal to another.
```suggestion
            Checks if an Age Restriction level is lower or equal to another.
```

2023-02-20 06:46 UTC, EmreTech commented on docs/api.rst
> +            Checks if a Age Restriction level is lower or equal to another.
```suggestion
            Checks if an Age Restriction level is lower or equal to another.
```

2023-02-20 06:46 UTC, EmreTech commented on docs/whats_new.rst
> +- DM channels are now recognised as age restricted in :func:`~.commands.is_nsfw` check.
I don't think it's necessary to update an older changelog to use newer terminology.

2023-02-20 06:46 UTC, EmreTech commented on nextcord/channel.py
> +        .. versionadded:: 2.5
```suggestion
        .. versionchanged:: 2.5
```

2023-02-20 06:46 UTC, EmreTech commented on nextcord/ext/commands/errors.py
> +        Renamed from ``NSFWChannelRequired`` to :exc:`AgeRestrictedChannelRequired`. ``NSFWChannelRequired`` is now an alias.
`versionadded` and `versionchanged` cannot be mixed in the same class.

2023-02-20 06:46 UTC, EmreTech commented on nextcord/ext/commands/errors.py
> +        The channel is not age restricted
```suggestion
        The channel is not age restricted.
```

2023-02-20 06:46 UTC, EmreTech commented on nextcord/ext/commands/errors.py
> +        The channel is not age restricted
```suggestion
        The channel is not age restricted.
```

2023-09-18 02:40 UTC, EmreTech commented
@Soheab any updates on this?

2023-09-18 12:38 UTC, Soheab commented
> @Soheab any updates on this?

Resolved all the reviews!

2023-09-18 20:32 UTC, EmreTech requested changes
Remember to update the all of the `versionadded` & `versionchanged` to be 2.6.

2023-09-18 20:32 UTC, EmreTech commented on nextcord/channel.py
> +        If this channel is age restricted.
```suggestion
        Whether the channel is age restricted.
```

2023-09-18 20:32 UTC, EmreTech commented on nextcord/channel.py
> +        If the channel is age restricted.
```suggestion
        Whether the channel is age restricted.
```

2023-09-18 20:32 UTC, EmreTech commented on nextcord/channel.py
> +            To check if the channel or the guild of that channel are age restricted, consider :meth:`.is_age_resricted` instead.
```suggestion
            To check whether the channel or the guild of that channel are age restricted, consider :meth:`.is_age_restricted` instead.
```

2023-09-18 20:32 UTC, EmreTech commented on nextcord/channel.py
> +        If the channel is age restricted.
```suggestion
        Whether the channel is age restricted.
```

2023-09-18 20:32 UTC, EmreTech commented on nextcord/channel.py
> +            To check if the channel or the guild of that channel are age restricted, consider :meth:`is_age_restricted` instead.
```suggestion
            To check whether the channel or the guild of that channel are age restricted, consider :meth:`is_age_restricted` instead.
```

2023-09-18 20:32 UTC, EmreTech commented on nextcord/ext/application_checks/errors.py
> +    There is an alias for this called ``ApplicationNSFWChannelRequired``
```suggestion
    There is an alias for this called ``ApplicationNSFWChannelRequired``.
```

2023-09-18 20:32 UTC, EmreTech commented on nextcord/ext/commands/errors.py
> +        The channel is not age restricted.
```suggestion
        The channel that is not age restricted.
```

2023-10-01 16:52 UTC, ooliver1 reviewed
Not all too sure about this, since the developer documentation uses "nsfw" all over, the field `nsfw` and the descriptions for those fields say "nsfw".

2023-10-10 14:03 UTC, Soheab commented
> Not all too sure about this, since the developer documentation uses "nsfw" all over, the field `nsfw` and the descriptions for those fields say "nsfw".

Afaik discord calls it "age restricted" or something similar in the UI, things like their ToS (and promotional material ?).

2023-11-05 12:11 UTC, Soheab commented
> > Not all too sure about this, since the developer documentation uses "nsfw" all over, the field `nsfw` and the descriptions for those fields say "nsfw".
> 
> Afaik discord calls it "age restricted" or something similar in the UI, things like their ToS (and promotional material ?).

Like the following on mobile
![Screenshot_20231105_130924_Discord.png](https://github.com/nextcord/nextcord/assets/33902984/961a9bd9-3866-4a41-8aa6-ef7fd24026fd)

2023-11-05 21:11 UTC, ooliver1 commented
The UI also says servers, but we use "guilds" as the terminology to match the Discord Developer docs.

2024-06-12 18:43 UTC, ooliver1 commented
Closed for now due to the above reason that the API naming is "nsfw" and not "age restricted".

2024-06-12 18:43 UTC, closed without merging