docs(flags): reword docs for `discord_certified_moderator`
nextcord/nextcord pull request #944
Opened 2022-12-09 11:04 UTC by toolifelesstocode

## Summary
- **Closes** GH-935

This rewords the documentation for `PublicUserFlags.discord_certified_moderator`.

## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2022-12-09 22:19 UTC, EmreTech approved these changes

2022-12-11 23:13 UTC, ooliver1 requested changes

2022-12-11 23:13 UTC, ooliver1 commented on nextcord/flags.py
> +        """:class:`bool`: Returns ``True`` if the user is in the Discord Moderator Programs Alumni.
```suggestion
        """:class:`bool`: Returns ``True`` if the user is a Discord Moderator Programs Alumni.
```
> **alumni**
> a former member of a group, company, or organization

2022-12-25 13:17 UTC, ooliver1 approved these changes

2022-12-25 13:17 UTC, merged