refactor: remove mutable paramter defaults
nextcord/nextcord pull request #959
Opened 2022-12-25 15:15 UTC by ooliver1

## Summary

Closes #815

## Checklist

- [x] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [x] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-12-25 15:57 UTC, EmreTech submitted a review, later dismissed
The documentation for `unpack_annotation` should be updated.

2022-12-25 23:10 UTC, Skelmis requested changes

2022-12-25 23:10 UTC, Skelmis commented on nextcord/application_command.py
> +    given_annotation: Any, annotated_list: Optional[List[type]]
```suggestion
    given_annotation: Any, annotated_list: Optional[List[type]] = None
```

2022-12-26 18:33 UTC, teaishealthy approved these changes
except for comments lgtm

2023-01-31 01:27 UTC, Skelmis approved these changes

2023-02-21 23:57 UTC, merged