feat: add role connections
nextcord/nextcord pull request #964
Opened 2023-01-06 22:01 UTC by ooliver1

## Summary

Since the majority of this is via OAuth2, there is little support to provide in nextcord right now.
<https://github.com/discord/discord-api-docs/commit/205ceb49ae80240024b62ebe5cc0ded92b21aaad>

## Checklist

- [ ] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
  - [x] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-01-06 23:29 UTC, EmreTech commented on nextcord/role_connections.py
> +        self.description_localizations = description_localizations
Why are there no type hints for these attributes?

2023-01-09 01:29 UTC, Skelmis requested changes

2023-01-09 01:29 UTC, Skelmis commented on nextcord/types/role_connections.py
> +    description_localizations: NotRequired[dict[str, str]]
```suggestion
    description_localizations: NotRequired[Dict[str, str]]
```

2023-01-11 16:23 UTC, ooliver1 commented
"Not many people" based off what? It is high because it covers parts of the API which are not already covered.

2023-02-08 00:26 UTC, EmreTech approved these changes

2023-02-08 18:02 UTC, Skelmis approved these changes

2023-02-08 20:02 UTC, merged