feat(StickerFormatType): add gif enum
nextcord/nextcord pull request #969
Opened 2023-01-09 21:19 UTC by toolifelesstocode

## Summary

- Implements discord/discord-api-docs#5833

## Checklist

- [ ] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-01-11 10:17 UTC, ooliver1 requested changes

2023-01-11 10:17 UTC, ooliver1 commented on docs/api.rst
> +        Represents a sticker with a GIF image.
```suggestion
        Represents a sticker with a GIF image.

        .. versionadded:: 2.4
```

2023-01-11 10:26 UTC, toolifelesstocode commented on docs/api.rst
> +        Represents a sticker with a GIF image.
https://github.com/nextcord/nextcord/pull/969/commits/baf46767d9fa8392d782af38225f7367d9999e18

2023-01-20 17:31 UTC, EmreTech approved these changes

2023-01-31 01:25 UTC, Skelmis approved these changes

2023-02-09 20:52 UTC, ooliver1 approved these changes

2023-02-09 20:52 UTC, merged