docs(app-cmds): document SlashCommandMixin.options
nextcord/nextcord pull request #986
Opened 2023-02-04 17:13 UTC by toolifelesstocode

## Summary

This adds a documentation for `SlashCommandMixin.options`.

## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2023-02-12 05:34 UTC, Skelmis reviewed
Is it also worthwhile doing the other mixins within the same PR.

Such as `AutocompleteOptionMixin`

2023-03-12 17:38 UTC, ooliver1 requested changes

2023-03-12 17:38 UTC, ooliver1 commented on nextcord/application_command.py
> +            ``.options`` is now a read-only property.
```suggestion
        .. versionchanged:: 2.5
            This is now a read-only property.
```

2023-03-12 17:38 UTC, ooliver1 commented on nextcord/application_command.py
> +        """Returns the options of the command.
```suggestion
        """Dict[:class:`str`, :class:`SlashCommandOption`]: Returns the options of the command.
```

2023-03-20 15:04 UTC, ooliver1 approved these changes

2023-04-09 13:15 UTC, Skelmis approved these changes

2023-04-09 13:15 UTC, merged