feat(flags): add missing MessageFlags values
nextcord/nextcord pull request #990
Opened 2023-02-08 21:31 UTC by ooliver1

## Summary

The suppress notifications option is from discord/discord-api-docs#5910.
Bitshifted values seemed to have been missed in #911 as this is a flag

## Checklist

- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
  - [x] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-02-12 05:17 UTC, Skelmis approved these changes

2023-02-12 14:54 UTC, ooliver1 commented
Is that not what #979 is?

2023-02-16 08:35 UTC, toolifelesstocode approved these changes
Not sure if you want to add it to 2.4 or 2.5. Everything else looks good to me

2023-04-09 13:11 UTC, Skelmis requested changes

2023-04-09 13:11 UTC, Skelmis commented on nextcord/flags.py
> +        .. versionadded:: 2.4
```suggestion
        .. versionadded:: 2.5
```

2023-04-09 13:11 UTC, Skelmis commented on nextcord/flags.py
> +        .. versionadded:: 2.4
```suggestion
        .. versionadded:: 2.5
```

2023-04-09 13:11 UTC, Skelmis commented on nextcord/flags.py
> +        .. versionadded:: 2.4
```suggestion
        .. versionadded:: 2.5
```

2023-04-09 13:12 UTC, Skelmis approved these changes

2023-06-14 21:49 UTC, EmreTech approved these changes

2023-06-14 21:52 UTC, merged