feat(raw-models): add guild and user attr to RawMemberRemoveEvent
nextcord/nextcord pull request #999
Opened 2023-02-23 10:50 UTC by ooliver1

## Summary

Previously, it was not possible to see what user left. This adds the attribute to `RawMemberRemoveEvent`, using a full user object ( :D finally a non-partial ) to get a full `User`.

## Checklist

- [x] If code changes were made then they have been tested.
  - [x] I have updated the documentation to reflect the changes.
  - [x] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-02-27 20:40 UTC, Skelmis approved these changes

2023-03-21 23:42 UTC, teaishealthy requested changes

2023-03-21 23:42 UTC, teaishealthy commented on nextcord/state.py
>              )
Remove this else block or update the log message as the event is still dispatched when the guild hasn't been found (raw.guild is None)

2023-08-08 17:21 UTC, teaishealthy approved these changes

2023-08-08 17:45 UTC, merged